catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# HLS run script generated by v++ compiler
# 

open_project kernel_wrapper
set_top kernel_wrapper
# v++ -g, -D, -I, --advanced.prop kernel.kernel_wrapper.kernel_flags
add_files "/home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/kernel_wrapper.cpp" -cflags " -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware/weights -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware/nnet_utils -std=c++11"
add_files "/home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware/myproject.cpp" -cflags " -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware/weights -I /home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/firmware/nnet_utils -std=c++11"
open_solution -flow_target vitis solution
set_part xcu55c-fsvh2892-2L-e
# v++ --hls.clock or --kernel_frequency
create_clock -period 200MHz -name default
# v++ --advanced.param compiler.hlsDataflowStrictMode
config_dataflow -strict_mode warning
# v++ --advanced.param compiler.deadlockDetection
config_export -deadlock_detection sim
# v++ --advanced.param compiler.axiDeadLockFree
config_interface -m_axi_conservative_mode=1
config_interface -m_axi_addr64
# v++ --hls.max_memory_ports
config_interface -m_axi_auto_max_ports=0
config_export -format xo -ipname kernel_wrapper
# v++ --hls.pre_tcl or --advanced.prop solution.hls_pre_tcl
source "/home/ayvol/vitis-accel-hw-quant/vitis_accel_prj/hls_config.tcl"
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
