// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_wrapper_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_42u_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer13_out_dout,
        layer13_out_num_data_valid,
        layer13_out_fifo_cap,
        layer13_out_empty_n,
        layer13_out_read,
        layer15_out_din,
        layer15_out_num_data_valid,
        layer15_out_fifo_cap,
        layer15_out_full_n,
        layer15_out_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [383:0] layer13_out_dout;
input  [2:0] layer13_out_num_data_valid;
input  [2:0] layer13_out_fifo_cap;
input   layer13_out_empty_n;
output   layer13_out_read;
output  [671:0] layer15_out_din;
input  [1:0] layer15_out_num_data_valid;
input  [1:0] layer15_out_fifo_cap;
input   layer15_out_full_n;
output   layer15_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer13_out_read;
reg layer15_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer13_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln36_fu_647_p2;
reg    layer15_out_blk_n;
wire    ap_CS_fsm_state5;
reg   [15:0] res_V_reg_2858;
wire    ap_CS_fsm_state4;
reg   [15:0] res_V_73_reg_2863;
reg   [15:0] res_V_74_reg_2868;
reg   [15:0] res_V_75_reg_2873;
reg   [15:0] res_V_76_reg_2878;
reg   [15:0] res_V_77_reg_2883;
reg   [15:0] res_V_78_reg_2888;
reg   [15:0] res_V_79_reg_2893;
reg   [15:0] res_V_80_reg_2898;
reg   [15:0] res_V_81_reg_2903;
reg   [15:0] res_V_82_reg_2908;
reg   [15:0] res_V_83_reg_2913;
reg   [15:0] res_V_84_reg_2918;
reg   [15:0] res_V_85_reg_2923;
reg   [15:0] res_V_86_reg_2928;
reg   [15:0] res_V_87_reg_2933;
reg   [15:0] res_V_88_reg_2938;
reg   [15:0] res_V_89_reg_2943;
reg   [15:0] res_V_90_reg_2948;
reg   [15:0] res_V_91_reg_2953;
reg   [15:0] res_V_92_reg_2958;
reg   [15:0] res_V_93_reg_2963;
reg   [15:0] res_V_94_reg_2968;
reg   [15:0] res_V_95_reg_2973;
reg   [15:0] res_V_96_reg_2978;
reg   [15:0] res_V_97_reg_2983;
reg   [15:0] res_V_98_reg_2988;
reg   [15:0] res_V_99_reg_2993;
reg   [15:0] res_V_100_reg_2998;
reg   [15:0] res_V_101_reg_3003;
reg   [15:0] res_V_102_reg_3008;
reg   [15:0] res_V_103_reg_3013;
reg   [15:0] res_V_104_reg_3018;
reg   [15:0] res_V_105_reg_3023;
reg   [15:0] res_V_106_reg_3028;
reg   [15:0] res_V_107_reg_3033;
reg   [15:0] res_V_108_reg_3038;
reg   [15:0] res_V_109_reg_3043;
reg   [15:0] res_V_110_reg_3048;
reg   [15:0] res_V_111_reg_3053;
reg   [15:0] res_V_112_reg_3058;
reg   [15:0] res_V_113_reg_3063;
wire    grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start;
wire    grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_done;
wire    grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_idle;
wire    grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_ready;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_0;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_1;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_2;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_3;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_4;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_5;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_6;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_7;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_8;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_9;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_10;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_11;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_12;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_13;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_14;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_15;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_16;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_17;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_18;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_19;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_20;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_21;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_22;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_23;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_24;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_25;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_26;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_27;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_28;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_29;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_30;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_31;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_32;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_33;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_34;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_35;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_36;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_37;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_38;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_39;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_40;
wire   [15:0] grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_41;
reg    grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [2:0] i_in_fu_138;
wire   [2:0] add_ln36_fu_653_p2;
reg    ap_block_state2;
reg    ap_block_state1;
reg   [15:0] data_V_fu_142;
wire   [15:0] trunc_ln40_fu_659_p1;
wire   [1:0] trunc_ln44_fu_893_p1;
reg   [15:0] data_V_101_fu_146;
reg   [15:0] data_V_102_fu_150;
reg   [15:0] data_V_103_fu_154;
reg   [15:0] data_V_104_fu_158;
reg   [15:0] data_V_105_fu_162;
reg   [15:0] data_V_106_fu_166;
reg   [15:0] data_V_107_fu_170;
reg   [15:0] data_V_108_fu_174;
reg   [15:0] data_V_109_fu_178;
reg   [15:0] data_V_110_fu_182;
reg   [15:0] data_V_111_fu_186;
reg   [15:0] data_V_112_fu_190;
reg   [15:0] data_V_113_fu_194;
reg   [15:0] data_V_114_fu_198;
reg   [15:0] data_V_115_fu_202;
reg   [15:0] data_V_116_fu_206;
reg   [15:0] data_V_117_fu_210;
reg   [15:0] data_V_118_fu_214;
reg   [15:0] data_V_119_fu_218;
reg   [15:0] data_V_120_fu_222;
reg   [15:0] data_V_121_fu_226;
reg   [15:0] data_V_122_fu_230;
reg   [15:0] data_V_123_fu_234;
reg   [15:0] data_V_124_fu_238;
reg   [15:0] data_V_125_fu_242;
reg   [15:0] data_V_126_fu_246;
reg   [15:0] data_V_127_fu_250;
reg   [15:0] data_V_128_fu_254;
reg   [15:0] data_V_129_fu_258;
reg   [15:0] data_V_130_fu_262;
reg   [15:0] data_V_131_fu_266;
reg   [15:0] data_V_132_fu_270;
reg   [15:0] data_V_133_fu_274;
reg   [15:0] data_V_134_fu_278;
reg   [15:0] data_V_135_fu_282;
reg   [15:0] data_V_136_fu_286;
reg   [15:0] data_V_137_fu_290;
reg   [15:0] data_V_138_fu_294;
reg   [15:0] data_V_139_fu_298;
reg   [15:0] data_V_140_fu_302;
reg   [15:0] data_V_141_fu_306;
reg   [15:0] data_V_142_fu_310;
reg   [15:0] data_V_143_fu_314;
reg   [15:0] data_V_144_fu_318;
reg   [15:0] data_V_145_fu_322;
reg   [15:0] data_V_146_fu_326;
reg   [15:0] data_V_147_fu_330;
reg   [15:0] data_V_148_fu_334;
reg   [15:0] data_V_149_fu_338;
reg   [15:0] data_V_150_fu_342;
reg   [15:0] data_V_151_fu_346;
reg   [15:0] data_V_152_fu_350;
reg   [15:0] data_V_153_fu_354;
reg   [15:0] data_V_154_fu_358;
reg   [15:0] data_V_155_fu_362;
reg   [15:0] data_V_156_fu_366;
reg   [15:0] data_V_157_fu_370;
reg   [15:0] data_V_158_fu_374;
reg   [15:0] data_V_159_fu_378;
reg   [15:0] data_V_160_fu_382;
reg   [15:0] data_V_161_fu_386;
reg   [15:0] data_V_162_fu_390;
reg   [15:0] data_V_163_fu_394;
reg   [15:0] data_V_164_fu_398;
reg   [15:0] data_V_165_fu_402;
reg   [15:0] data_V_166_fu_406;
reg   [15:0] data_V_167_fu_410;
reg   [15:0] data_V_168_fu_414;
reg   [15:0] data_V_169_fu_418;
reg   [15:0] data_V_170_fu_422;
reg   [15:0] data_V_171_fu_426;
reg   [15:0] data_V_172_fu_430;
reg   [15:0] data_V_173_fu_434;
reg   [15:0] data_V_174_fu_438;
reg   [15:0] data_V_175_fu_442;
reg   [15:0] data_V_176_fu_446;
reg   [15:0] data_V_177_fu_450;
reg   [15:0] data_V_178_fu_454;
reg   [15:0] data_V_179_fu_458;
reg   [15:0] data_V_180_fu_462;
reg   [15:0] data_V_181_fu_466;
reg   [15:0] data_V_182_fu_470;
reg   [15:0] data_V_183_fu_474;
reg   [15:0] data_V_184_fu_478;
reg   [15:0] data_V_185_fu_482;
reg   [15:0] data_V_186_fu_486;
reg   [15:0] data_V_187_fu_490;
reg   [15:0] data_V_188_fu_494;
reg   [15:0] data_V_189_fu_498;
reg   [15:0] data_V_190_fu_502;
reg   [15:0] data_V_191_fu_506;
reg   [15:0] data_V_192_fu_510;
reg   [15:0] data_V_193_fu_514;
reg   [15:0] data_V_194_fu_518;
reg   [15:0] data_V_195_fu_522;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg = 1'b0;
end

kernel_wrapper_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start),
    .ap_done(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_done),
    .ap_idle(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_idle),
    .ap_ready(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_ready),
    .p_read(data_V_148_fu_334),
    .p_read1(data_V_149_fu_338),
    .p_read2(data_V_150_fu_342),
    .p_read3(data_V_151_fu_346),
    .p_read4(data_V_152_fu_350),
    .p_read5(data_V_153_fu_354),
    .p_read6(data_V_154_fu_358),
    .p_read7(data_V_155_fu_362),
    .p_read8(data_V_156_fu_366),
    .p_read9(data_V_157_fu_370),
    .p_read10(data_V_158_fu_374),
    .p_read11(data_V_159_fu_378),
    .p_read12(data_V_160_fu_382),
    .p_read13(data_V_161_fu_386),
    .p_read14(data_V_162_fu_390),
    .p_read15(data_V_163_fu_394),
    .p_read16(data_V_164_fu_398),
    .p_read17(data_V_165_fu_402),
    .p_read18(data_V_166_fu_406),
    .p_read19(data_V_167_fu_410),
    .p_read20(data_V_168_fu_414),
    .p_read21(data_V_169_fu_418),
    .p_read22(data_V_170_fu_422),
    .p_read23(data_V_171_fu_426),
    .p_read24(data_V_124_fu_238),
    .p_read25(data_V_125_fu_242),
    .p_read26(data_V_126_fu_246),
    .p_read27(data_V_127_fu_250),
    .p_read28(data_V_128_fu_254),
    .p_read29(data_V_129_fu_258),
    .p_read30(data_V_130_fu_262),
    .p_read31(data_V_131_fu_266),
    .p_read32(data_V_132_fu_270),
    .p_read33(data_V_133_fu_274),
    .p_read34(data_V_134_fu_278),
    .p_read35(data_V_135_fu_282),
    .p_read36(data_V_136_fu_286),
    .p_read37(data_V_137_fu_290),
    .p_read38(data_V_138_fu_294),
    .p_read39(data_V_139_fu_298),
    .p_read40(data_V_140_fu_302),
    .p_read41(data_V_141_fu_306),
    .p_read42(data_V_142_fu_310),
    .p_read43(data_V_143_fu_314),
    .p_read44(data_V_144_fu_318),
    .p_read45(data_V_145_fu_322),
    .p_read46(data_V_146_fu_326),
    .p_read47(data_V_147_fu_330),
    .p_read48(data_V_fu_142),
    .p_read49(data_V_101_fu_146),
    .p_read50(data_V_102_fu_150),
    .p_read51(data_V_103_fu_154),
    .p_read52(data_V_104_fu_158),
    .p_read53(data_V_105_fu_162),
    .p_read54(data_V_106_fu_166),
    .p_read55(data_V_107_fu_170),
    .p_read56(data_V_108_fu_174),
    .p_read57(data_V_109_fu_178),
    .p_read58(data_V_110_fu_182),
    .p_read59(data_V_111_fu_186),
    .p_read60(data_V_112_fu_190),
    .p_read61(data_V_113_fu_194),
    .p_read62(data_V_114_fu_198),
    .p_read63(data_V_115_fu_202),
    .p_read64(data_V_116_fu_206),
    .p_read65(data_V_117_fu_210),
    .p_read66(data_V_118_fu_214),
    .p_read67(data_V_119_fu_218),
    .p_read68(data_V_120_fu_222),
    .p_read69(data_V_121_fu_226),
    .p_read70(data_V_122_fu_230),
    .p_read71(data_V_123_fu_234),
    .p_read72(data_V_172_fu_430),
    .p_read73(data_V_173_fu_434),
    .p_read74(data_V_174_fu_438),
    .p_read75(data_V_175_fu_442),
    .p_read76(data_V_176_fu_446),
    .p_read77(data_V_177_fu_450),
    .p_read78(data_V_178_fu_454),
    .p_read79(data_V_179_fu_458),
    .p_read80(data_V_180_fu_462),
    .p_read81(data_V_181_fu_466),
    .p_read82(data_V_182_fu_470),
    .p_read83(data_V_183_fu_474),
    .p_read84(data_V_184_fu_478),
    .p_read85(data_V_185_fu_482),
    .p_read86(data_V_186_fu_486),
    .p_read87(data_V_187_fu_490),
    .p_read88(data_V_188_fu_494),
    .p_read89(data_V_189_fu_498),
    .p_read90(data_V_190_fu_502),
    .p_read91(data_V_191_fu_506),
    .p_read92(data_V_192_fu_510),
    .p_read93(data_V_193_fu_514),
    .p_read94(data_V_194_fu_518),
    .p_read95(data_V_195_fu_522),
    .ap_return_0(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_0),
    .ap_return_1(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_1),
    .ap_return_2(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_2),
    .ap_return_3(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_3),
    .ap_return_4(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_4),
    .ap_return_5(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_5),
    .ap_return_6(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_6),
    .ap_return_7(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_7),
    .ap_return_8(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_8),
    .ap_return_9(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_9),
    .ap_return_10(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_10),
    .ap_return_11(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_11),
    .ap_return_12(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_12),
    .ap_return_13(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_13),
    .ap_return_14(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_14),
    .ap_return_15(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_15),
    .ap_return_16(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_16),
    .ap_return_17(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_17),
    .ap_return_18(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_18),
    .ap_return_19(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_19),
    .ap_return_20(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_20),
    .ap_return_21(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_21),
    .ap_return_22(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_22),
    .ap_return_23(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_23),
    .ap_return_24(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_24),
    .ap_return_25(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_25),
    .ap_return_26(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_26),
    .ap_return_27(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_27),
    .ap_return_28(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_28),
    .ap_return_29(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_29),
    .ap_return_30(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_30),
    .ap_return_31(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_31),
    .ap_return_32(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_32),
    .ap_return_33(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_33),
    .ap_return_34(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_34),
    .ap_return_35(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_35),
    .ap_return_36(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_36),
    .ap_return_37(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_37),
    .ap_return_38(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_38),
    .ap_return_39(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_39),
    .ap_return_40(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_40),
    .ap_return_41(grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_41)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg <= 1'b1;
        end else if ((grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_ready == 1'b1)) begin
            grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_in_fu_138 <= 3'd0;
    end else if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_in_fu_138 <= add_ln36_fu_653_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (trunc_ln44_fu_893_p1 == 2'd2) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_101_fu_146 <= {{layer13_out_dout[31:16]}};
        data_V_102_fu_150 <= {{layer13_out_dout[47:32]}};
        data_V_103_fu_154 <= {{layer13_out_dout[63:48]}};
        data_V_104_fu_158 <= {{layer13_out_dout[79:64]}};
        data_V_105_fu_162 <= {{layer13_out_dout[95:80]}};
        data_V_106_fu_166 <= {{layer13_out_dout[111:96]}};
        data_V_107_fu_170 <= {{layer13_out_dout[127:112]}};
        data_V_108_fu_174 <= {{layer13_out_dout[143:128]}};
        data_V_109_fu_178 <= {{layer13_out_dout[159:144]}};
        data_V_110_fu_182 <= {{layer13_out_dout[175:160]}};
        data_V_111_fu_186 <= {{layer13_out_dout[191:176]}};
        data_V_112_fu_190 <= {{layer13_out_dout[207:192]}};
        data_V_113_fu_194 <= {{layer13_out_dout[223:208]}};
        data_V_114_fu_198 <= {{layer13_out_dout[239:224]}};
        data_V_115_fu_202 <= {{layer13_out_dout[255:240]}};
        data_V_116_fu_206 <= {{layer13_out_dout[271:256]}};
        data_V_117_fu_210 <= {{layer13_out_dout[287:272]}};
        data_V_118_fu_214 <= {{layer13_out_dout[303:288]}};
        data_V_119_fu_218 <= {{layer13_out_dout[319:304]}};
        data_V_120_fu_222 <= {{layer13_out_dout[335:320]}};
        data_V_121_fu_226 <= {{layer13_out_dout[351:336]}};
        data_V_122_fu_230 <= {{layer13_out_dout[367:352]}};
        data_V_123_fu_234 <= {{layer13_out_dout[383:368]}};
        data_V_fu_142 <= trunc_ln40_fu_659_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (trunc_ln44_fu_893_p1 == 2'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_124_fu_238 <= trunc_ln40_fu_659_p1;
        data_V_125_fu_242 <= {{layer13_out_dout[31:16]}};
        data_V_126_fu_246 <= {{layer13_out_dout[47:32]}};
        data_V_127_fu_250 <= {{layer13_out_dout[63:48]}};
        data_V_128_fu_254 <= {{layer13_out_dout[79:64]}};
        data_V_129_fu_258 <= {{layer13_out_dout[95:80]}};
        data_V_130_fu_262 <= {{layer13_out_dout[111:96]}};
        data_V_131_fu_266 <= {{layer13_out_dout[127:112]}};
        data_V_132_fu_270 <= {{layer13_out_dout[143:128]}};
        data_V_133_fu_274 <= {{layer13_out_dout[159:144]}};
        data_V_134_fu_278 <= {{layer13_out_dout[175:160]}};
        data_V_135_fu_282 <= {{layer13_out_dout[191:176]}};
        data_V_136_fu_286 <= {{layer13_out_dout[207:192]}};
        data_V_137_fu_290 <= {{layer13_out_dout[223:208]}};
        data_V_138_fu_294 <= {{layer13_out_dout[239:224]}};
        data_V_139_fu_298 <= {{layer13_out_dout[255:240]}};
        data_V_140_fu_302 <= {{layer13_out_dout[271:256]}};
        data_V_141_fu_306 <= {{layer13_out_dout[287:272]}};
        data_V_142_fu_310 <= {{layer13_out_dout[303:288]}};
        data_V_143_fu_314 <= {{layer13_out_dout[319:304]}};
        data_V_144_fu_318 <= {{layer13_out_dout[335:320]}};
        data_V_145_fu_322 <= {{layer13_out_dout[351:336]}};
        data_V_146_fu_326 <= {{layer13_out_dout[367:352]}};
        data_V_147_fu_330 <= {{layer13_out_dout[383:368]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (trunc_ln44_fu_893_p1 == 2'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_148_fu_334 <= trunc_ln40_fu_659_p1;
        data_V_149_fu_338 <= {{layer13_out_dout[31:16]}};
        data_V_150_fu_342 <= {{layer13_out_dout[47:32]}};
        data_V_151_fu_346 <= {{layer13_out_dout[63:48]}};
        data_V_152_fu_350 <= {{layer13_out_dout[79:64]}};
        data_V_153_fu_354 <= {{layer13_out_dout[95:80]}};
        data_V_154_fu_358 <= {{layer13_out_dout[111:96]}};
        data_V_155_fu_362 <= {{layer13_out_dout[127:112]}};
        data_V_156_fu_366 <= {{layer13_out_dout[143:128]}};
        data_V_157_fu_370 <= {{layer13_out_dout[159:144]}};
        data_V_158_fu_374 <= {{layer13_out_dout[175:160]}};
        data_V_159_fu_378 <= {{layer13_out_dout[191:176]}};
        data_V_160_fu_382 <= {{layer13_out_dout[207:192]}};
        data_V_161_fu_386 <= {{layer13_out_dout[223:208]}};
        data_V_162_fu_390 <= {{layer13_out_dout[239:224]}};
        data_V_163_fu_394 <= {{layer13_out_dout[255:240]}};
        data_V_164_fu_398 <= {{layer13_out_dout[271:256]}};
        data_V_165_fu_402 <= {{layer13_out_dout[287:272]}};
        data_V_166_fu_406 <= {{layer13_out_dout[303:288]}};
        data_V_167_fu_410 <= {{layer13_out_dout[319:304]}};
        data_V_168_fu_414 <= {{layer13_out_dout[335:320]}};
        data_V_169_fu_418 <= {{layer13_out_dout[351:336]}};
        data_V_170_fu_422 <= {{layer13_out_dout[367:352]}};
        data_V_171_fu_426 <= {{layer13_out_dout[383:368]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (trunc_ln44_fu_893_p1 == 2'd3) & (1'b1 == ap_CS_fsm_state2))) begin
        data_V_172_fu_430 <= trunc_ln40_fu_659_p1;
        data_V_173_fu_434 <= {{layer13_out_dout[31:16]}};
        data_V_174_fu_438 <= {{layer13_out_dout[47:32]}};
        data_V_175_fu_442 <= {{layer13_out_dout[63:48]}};
        data_V_176_fu_446 <= {{layer13_out_dout[79:64]}};
        data_V_177_fu_450 <= {{layer13_out_dout[95:80]}};
        data_V_178_fu_454 <= {{layer13_out_dout[111:96]}};
        data_V_179_fu_458 <= {{layer13_out_dout[127:112]}};
        data_V_180_fu_462 <= {{layer13_out_dout[143:128]}};
        data_V_181_fu_466 <= {{layer13_out_dout[159:144]}};
        data_V_182_fu_470 <= {{layer13_out_dout[175:160]}};
        data_V_183_fu_474 <= {{layer13_out_dout[191:176]}};
        data_V_184_fu_478 <= {{layer13_out_dout[207:192]}};
        data_V_185_fu_482 <= {{layer13_out_dout[223:208]}};
        data_V_186_fu_486 <= {{layer13_out_dout[239:224]}};
        data_V_187_fu_490 <= {{layer13_out_dout[255:240]}};
        data_V_188_fu_494 <= {{layer13_out_dout[271:256]}};
        data_V_189_fu_498 <= {{layer13_out_dout[287:272]}};
        data_V_190_fu_502 <= {{layer13_out_dout[303:288]}};
        data_V_191_fu_506 <= {{layer13_out_dout[319:304]}};
        data_V_192_fu_510 <= {{layer13_out_dout[335:320]}};
        data_V_193_fu_514 <= {{layer13_out_dout[351:336]}};
        data_V_194_fu_518 <= {{layer13_out_dout[367:352]}};
        data_V_195_fu_522 <= {{layer13_out_dout[383:368]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        res_V_100_reg_2998 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_28;
        res_V_101_reg_3003 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_29;
        res_V_102_reg_3008 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_30;
        res_V_103_reg_3013 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_31;
        res_V_104_reg_3018 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_32;
        res_V_105_reg_3023 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_33;
        res_V_106_reg_3028 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_34;
        res_V_107_reg_3033 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_35;
        res_V_108_reg_3038 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_36;
        res_V_109_reg_3043 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_37;
        res_V_110_reg_3048 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_38;
        res_V_111_reg_3053 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_39;
        res_V_112_reg_3058 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_40;
        res_V_113_reg_3063 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_41;
        res_V_73_reg_2863 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_1;
        res_V_74_reg_2868 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_2;
        res_V_75_reg_2873 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_3;
        res_V_76_reg_2878 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_4;
        res_V_77_reg_2883 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_5;
        res_V_78_reg_2888 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_6;
        res_V_79_reg_2893 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_7;
        res_V_80_reg_2898 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_8;
        res_V_81_reg_2903 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_9;
        res_V_82_reg_2908 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_10;
        res_V_83_reg_2913 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_11;
        res_V_84_reg_2918 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_12;
        res_V_85_reg_2923 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_13;
        res_V_86_reg_2928 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_14;
        res_V_87_reg_2933 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_15;
        res_V_88_reg_2938 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_16;
        res_V_89_reg_2943 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_17;
        res_V_90_reg_2948 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_18;
        res_V_91_reg_2953 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_19;
        res_V_92_reg_2958 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_20;
        res_V_93_reg_2963 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_21;
        res_V_94_reg_2968 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_22;
        res_V_95_reg_2973 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_23;
        res_V_96_reg_2978 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_24;
        res_V_97_reg_2983 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_25;
        res_V_98_reg_2988 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_26;
        res_V_99_reg_2993 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_27;
        res_V_reg_2858 <= grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_return_0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer15_out_full_n == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_blk_n = layer13_out_empty_n;
    end else begin
        layer13_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer13_out_read = 1'b1;
    end else begin
        layer13_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        layer15_out_blk_n = layer15_out_full_n;
    end else begin
        layer15_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        layer15_out_write = 1'b1;
    end else begin
        layer15_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0)) & (icmp_ln36_fu_647_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((layer15_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_653_p2 = (i_in_fu_138 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((icmp_ln36_fu_647_p2 == 1'd0) & (layer13_out_empty_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start = grp_dense_wrapper_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config15_s_fu_539_ap_start_reg;

assign icmp_ln36_fu_647_p2 = ((i_in_fu_138 == 3'd4) ? 1'b1 : 1'b0);

assign layer15_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_V_113_reg_3063}, {res_V_112_reg_3058}}, {res_V_111_reg_3053}}, {res_V_110_reg_3048}}, {res_V_109_reg_3043}}, {res_V_108_reg_3038}}, {res_V_107_reg_3033}}, {res_V_106_reg_3028}}, {res_V_105_reg_3023}}, {res_V_104_reg_3018}}, {res_V_103_reg_3013}}, {res_V_102_reg_3008}}, {res_V_101_reg_3003}}, {res_V_100_reg_2998}}, {res_V_99_reg_2993}}, {res_V_98_reg_2988}}, {res_V_97_reg_2983}}, {res_V_96_reg_2978}}, {res_V_95_reg_2973}}, {res_V_94_reg_2968}}, {res_V_93_reg_2963}}, {res_V_92_reg_2958}}, {res_V_91_reg_2953}}, {res_V_90_reg_2948}}, {res_V_89_reg_2943}}, {res_V_88_reg_2938}}, {res_V_87_reg_2933}}, {res_V_86_reg_2928}}, {res_V_85_reg_2923}}, {res_V_84_reg_2918}}, {res_V_83_reg_2913}}, {res_V_82_reg_2908}}, {res_V_81_reg_2903}}, {res_V_80_reg_2898}}, {res_V_79_reg_2893}}, {res_V_78_reg_2888}}, {res_V_77_reg_2883}}, {res_V_76_reg_2878}}, {res_V_75_reg_2873}}, {res_V_74_reg_2868}}, {res_V_73_reg_2863}}, {res_V_reg_2858}};

assign start_out = real_start;

assign trunc_ln40_fu_659_p1 = layer13_out_dout[15:0];

assign trunc_ln44_fu_893_p1 = i_in_fu_138[1:0];

endmodule //kernel_wrapper_dense_array_ap_fixed_24u_array_ap_fixed_16_6_5_3_0_42u_config15_s
