// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_wrapper_dense_array_ap_ufixed_42u_array_ap_fixed_16_6_5_3_0_64u_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer18_out_dout,
        layer18_out_num_data_valid,
        layer18_out_fifo_cap,
        layer18_out_empty_n,
        layer18_out_read,
        layer19_out_din,
        layer19_out_num_data_valid,
        layer19_out_fifo_cap,
        layer19_out_full_n,
        layer19_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [251:0] layer18_out_dout;
input  [1:0] layer18_out_num_data_valid;
input  [1:0] layer18_out_fifo_cap;
input   layer18_out_empty_n;
output   layer18_out_read;
output  [1023:0] layer19_out_din;
input  [1:0] layer19_out_num_data_valid;
input  [1:0] layer19_out_fifo_cap;
input   layer19_out_full_n;
output   layer19_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer18_out_read;
reg layer19_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer18_out_blk_n;
reg    layer19_out_blk_n;
wire    ap_CS_fsm_state4;
wire   [5:0] data_V_fu_247_p1;
reg   [5:0] data_V_reg_986;
reg   [5:0] data_V_101_reg_991;
reg   [5:0] data_V_3_reg_996;
reg   [5:0] data_V_63_reg_1001;
reg   [5:0] data_V_64_reg_1006;
reg   [5:0] data_V_65_reg_1011;
reg   [5:0] data_V_66_reg_1016;
reg   [5:0] data_V_67_reg_1021;
reg   [5:0] data_V_68_reg_1026;
reg   [5:0] data_V_69_reg_1031;
reg   [5:0] data_V_70_reg_1036;
reg   [5:0] data_V_71_reg_1041;
reg   [5:0] data_V_72_reg_1046;
reg   [5:0] data_V_73_reg_1051;
reg   [5:0] data_V_74_reg_1056;
reg   [5:0] data_V_75_reg_1061;
reg   [5:0] data_V_76_reg_1066;
reg   [5:0] data_V_77_reg_1071;
reg   [5:0] data_V_78_reg_1076;
reg   [5:0] data_V_79_reg_1081;
reg   [5:0] data_V_80_reg_1086;
reg   [5:0] data_V_81_reg_1091;
reg   [5:0] data_V_82_reg_1096;
reg   [5:0] data_V_83_reg_1101;
reg   [5:0] data_V_84_reg_1106;
reg   [5:0] data_V_85_reg_1111;
reg   [5:0] data_V_86_reg_1116;
reg   [5:0] data_V_87_reg_1121;
reg   [5:0] data_V_88_reg_1126;
reg   [5:0] data_V_89_reg_1131;
reg   [5:0] data_V_90_reg_1136;
reg   [5:0] data_V_91_reg_1141;
reg   [5:0] data_V_92_reg_1146;
reg   [5:0] data_V_93_reg_1151;
reg   [5:0] data_V_94_reg_1156;
reg   [5:0] data_V_95_reg_1161;
reg   [5:0] data_V_96_reg_1166;
reg   [5:0] data_V_97_reg_1171;
reg   [5:0] data_V_98_reg_1176;
reg   [5:0] data_V_99_reg_1181;
reg   [5:0] data_V_100_reg_1186;
reg   [5:0] data_V_4_reg_1191;
reg   [15:0] res_V_reg_1196;
wire    ap_CS_fsm_state3;
reg   [15:0] res_V_10_reg_1201;
reg   [15:0] res_V_11_reg_1206;
reg   [15:0] res_V_12_reg_1211;
reg   [15:0] res_V_13_reg_1216;
reg   [15:0] res_V_14_reg_1221;
reg   [15:0] res_V_15_reg_1226;
reg   [15:0] res_V_16_reg_1231;
reg   [15:0] res_V_17_reg_1236;
reg   [15:0] res_V_18_reg_1241;
reg   [15:0] res_V_19_reg_1246;
reg   [15:0] res_V_20_reg_1251;
reg   [15:0] res_V_21_reg_1256;
reg   [15:0] res_V_22_reg_1261;
reg   [15:0] res_V_23_reg_1266;
reg   [15:0] res_V_24_reg_1271;
reg   [15:0] res_V_25_reg_1276;
reg   [15:0] res_V_26_reg_1281;
reg   [15:0] res_V_27_reg_1286;
reg   [15:0] res_V_28_reg_1291;
reg   [15:0] res_V_29_reg_1296;
reg   [15:0] res_V_30_reg_1301;
reg   [15:0] res_V_31_reg_1306;
reg   [15:0] res_V_32_reg_1311;
reg   [15:0] res_V_33_reg_1316;
reg   [15:0] res_V_34_reg_1321;
reg   [15:0] res_V_35_reg_1326;
reg   [15:0] res_V_36_reg_1331;
reg   [15:0] res_V_37_reg_1336;
reg   [15:0] res_V_38_reg_1341;
reg   [15:0] res_V_39_reg_1346;
reg   [15:0] res_V_40_reg_1351;
reg   [15:0] res_V_41_reg_1356;
reg   [15:0] res_V_42_reg_1361;
reg   [15:0] res_V_43_reg_1366;
reg   [15:0] res_V_44_reg_1371;
reg   [15:0] res_V_45_reg_1376;
reg   [15:0] res_V_46_reg_1381;
reg   [15:0] res_V_47_reg_1386;
reg   [15:0] res_V_48_reg_1391;
reg   [15:0] res_V_49_reg_1396;
reg   [15:0] res_V_50_reg_1401;
reg   [15:0] res_V_51_reg_1406;
reg   [15:0] res_V_52_reg_1411;
reg   [15:0] res_V_53_reg_1416;
reg   [15:0] res_V_54_reg_1421;
reg   [15:0] res_V_55_reg_1426;
reg   [15:0] res_V_56_reg_1431;
reg   [15:0] res_V_57_reg_1436;
reg   [15:0] res_V_58_reg_1441;
reg   [15:0] res_V_59_reg_1446;
reg   [15:0] res_V_60_reg_1451;
reg   [15:0] res_V_61_reg_1456;
reg   [15:0] res_V_62_reg_1461;
reg   [15:0] res_V_63_reg_1466;
reg   [15:0] res_V_64_reg_1471;
reg   [15:0] res_V_65_reg_1476;
reg   [15:0] res_V_66_reg_1481;
reg   [15:0] res_V_67_reg_1486;
reg   [15:0] res_V_68_reg_1491;
reg   [15:0] res_V_69_reg_1496;
reg   [15:0] res_V_70_reg_1501;
reg   [15:0] res_V_71_reg_1506;
reg   [15:0] res_V_72_reg_1511;
wire    grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start;
wire    grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_done;
wire    grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_idle;
wire    grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_ready;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_0;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_1;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_2;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_3;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_4;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_5;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_6;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_7;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_8;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_9;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_10;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_11;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_12;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_13;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_14;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_15;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_16;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_17;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_18;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_19;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_20;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_21;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_22;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_23;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_24;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_25;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_26;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_27;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_28;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_29;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_30;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_31;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_32;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_33;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_34;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_35;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_36;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_37;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_38;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_39;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_40;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_41;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_42;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_43;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_44;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_45;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_46;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_47;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_48;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_49;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_50;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_51;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_52;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_53;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_54;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_55;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_56;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_57;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_58;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_59;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_60;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_61;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_62;
wire   [15:0] grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_63;
reg    grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg = 1'b0;
end

kernel_wrapper_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start),
    .ap_done(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_done),
    .ap_idle(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_idle),
    .ap_ready(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_ready),
    .p_read(data_V_reg_986),
    .p_read1(data_V_63_reg_1001),
    .p_read2(data_V_64_reg_1006),
    .p_read3(data_V_65_reg_1011),
    .p_read4(data_V_66_reg_1016),
    .p_read5(data_V_67_reg_1021),
    .p_read6(data_V_68_reg_1026),
    .p_read7(data_V_69_reg_1031),
    .p_read8(data_V_70_reg_1036),
    .p_read9(data_V_71_reg_1041),
    .p_read10(data_V_72_reg_1046),
    .p_read11(data_V_73_reg_1051),
    .p_read12(data_V_74_reg_1056),
    .p_read13(data_V_75_reg_1061),
    .p_read14(data_V_76_reg_1066),
    .p_read15(data_V_77_reg_1071),
    .p_read16(data_V_78_reg_1076),
    .p_read17(data_V_79_reg_1081),
    .p_read18(data_V_80_reg_1086),
    .p_read19(data_V_81_reg_1091),
    .p_read20(data_V_82_reg_1096),
    .p_read21(data_V_83_reg_1101),
    .p_read22(data_V_84_reg_1106),
    .p_read23(data_V_85_reg_1111),
    .p_read24(data_V_86_reg_1116),
    .p_read25(data_V_87_reg_1121),
    .p_read26(data_V_88_reg_1126),
    .p_read27(data_V_89_reg_1131),
    .p_read28(data_V_90_reg_1136),
    .p_read29(data_V_91_reg_1141),
    .p_read30(data_V_92_reg_1146),
    .p_read31(data_V_93_reg_1151),
    .p_read32(data_V_94_reg_1156),
    .p_read33(data_V_95_reg_1161),
    .p_read34(data_V_96_reg_1166),
    .p_read35(data_V_97_reg_1171),
    .p_read36(data_V_98_reg_1176),
    .p_read37(data_V_99_reg_1181),
    .p_read38(data_V_100_reg_1186),
    .p_read39(data_V_4_reg_1191),
    .p_read40(data_V_101_reg_991),
    .p_read41(data_V_3_reg_996),
    .ap_return_0(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_0),
    .ap_return_1(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_1),
    .ap_return_2(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_2),
    .ap_return_3(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_3),
    .ap_return_4(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_4),
    .ap_return_5(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_5),
    .ap_return_6(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_6),
    .ap_return_7(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_7),
    .ap_return_8(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_8),
    .ap_return_9(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_9),
    .ap_return_10(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_10),
    .ap_return_11(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_11),
    .ap_return_12(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_12),
    .ap_return_13(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_13),
    .ap_return_14(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_14),
    .ap_return_15(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_15),
    .ap_return_16(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_16),
    .ap_return_17(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_17),
    .ap_return_18(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_18),
    .ap_return_19(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_19),
    .ap_return_20(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_20),
    .ap_return_21(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_21),
    .ap_return_22(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_22),
    .ap_return_23(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_23),
    .ap_return_24(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_24),
    .ap_return_25(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_25),
    .ap_return_26(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_26),
    .ap_return_27(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_27),
    .ap_return_28(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_28),
    .ap_return_29(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_29),
    .ap_return_30(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_30),
    .ap_return_31(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_31),
    .ap_return_32(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_32),
    .ap_return_33(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_33),
    .ap_return_34(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_34),
    .ap_return_35(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_35),
    .ap_return_36(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_36),
    .ap_return_37(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_37),
    .ap_return_38(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_38),
    .ap_return_39(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_39),
    .ap_return_40(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_40),
    .ap_return_41(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_41),
    .ap_return_42(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_42),
    .ap_return_43(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_43),
    .ap_return_44(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_44),
    .ap_return_45(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_45),
    .ap_return_46(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_46),
    .ap_return_47(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_47),
    .ap_return_48(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_48),
    .ap_return_49(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_49),
    .ap_return_50(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_50),
    .ap_return_51(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_51),
    .ap_return_52(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_52),
    .ap_return_53(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_53),
    .ap_return_54(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_54),
    .ap_return_55(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_55),
    .ap_return_56(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_56),
    .ap_return_57(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_57),
    .ap_return_58(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_58),
    .ap_return_59(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_59),
    .ap_return_60(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_60),
    .ap_return_61(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_61),
    .ap_return_62(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_62),
    .ap_return_63(grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_63)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_ready == 1'b1)) begin
            grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_100_reg_1186 <= {{layer18_out_dout[233:228]}};
        data_V_101_reg_991 <= {{layer18_out_dout[245:240]}};
        data_V_3_reg_996 <= {{layer18_out_dout[251:246]}};
        data_V_4_reg_1191 <= {{layer18_out_dout[239:234]}};
        data_V_63_reg_1001 <= {{layer18_out_dout[11:6]}};
        data_V_64_reg_1006 <= {{layer18_out_dout[17:12]}};
        data_V_65_reg_1011 <= {{layer18_out_dout[23:18]}};
        data_V_66_reg_1016 <= {{layer18_out_dout[29:24]}};
        data_V_67_reg_1021 <= {{layer18_out_dout[35:30]}};
        data_V_68_reg_1026 <= {{layer18_out_dout[41:36]}};
        data_V_69_reg_1031 <= {{layer18_out_dout[47:42]}};
        data_V_70_reg_1036 <= {{layer18_out_dout[53:48]}};
        data_V_71_reg_1041 <= {{layer18_out_dout[59:54]}};
        data_V_72_reg_1046 <= {{layer18_out_dout[65:60]}};
        data_V_73_reg_1051 <= {{layer18_out_dout[71:66]}};
        data_V_74_reg_1056 <= {{layer18_out_dout[77:72]}};
        data_V_75_reg_1061 <= {{layer18_out_dout[83:78]}};
        data_V_76_reg_1066 <= {{layer18_out_dout[89:84]}};
        data_V_77_reg_1071 <= {{layer18_out_dout[95:90]}};
        data_V_78_reg_1076 <= {{layer18_out_dout[101:96]}};
        data_V_79_reg_1081 <= {{layer18_out_dout[107:102]}};
        data_V_80_reg_1086 <= {{layer18_out_dout[113:108]}};
        data_V_81_reg_1091 <= {{layer18_out_dout[119:114]}};
        data_V_82_reg_1096 <= {{layer18_out_dout[125:120]}};
        data_V_83_reg_1101 <= {{layer18_out_dout[131:126]}};
        data_V_84_reg_1106 <= {{layer18_out_dout[137:132]}};
        data_V_85_reg_1111 <= {{layer18_out_dout[143:138]}};
        data_V_86_reg_1116 <= {{layer18_out_dout[149:144]}};
        data_V_87_reg_1121 <= {{layer18_out_dout[155:150]}};
        data_V_88_reg_1126 <= {{layer18_out_dout[161:156]}};
        data_V_89_reg_1131 <= {{layer18_out_dout[167:162]}};
        data_V_90_reg_1136 <= {{layer18_out_dout[173:168]}};
        data_V_91_reg_1141 <= {{layer18_out_dout[179:174]}};
        data_V_92_reg_1146 <= {{layer18_out_dout[185:180]}};
        data_V_93_reg_1151 <= {{layer18_out_dout[191:186]}};
        data_V_94_reg_1156 <= {{layer18_out_dout[197:192]}};
        data_V_95_reg_1161 <= {{layer18_out_dout[203:198]}};
        data_V_96_reg_1166 <= {{layer18_out_dout[209:204]}};
        data_V_97_reg_1171 <= {{layer18_out_dout[215:210]}};
        data_V_98_reg_1176 <= {{layer18_out_dout[221:216]}};
        data_V_99_reg_1181 <= {{layer18_out_dout[227:222]}};
        data_V_reg_986 <= data_V_fu_247_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        res_V_10_reg_1201 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_1;
        res_V_11_reg_1206 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_2;
        res_V_12_reg_1211 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_3;
        res_V_13_reg_1216 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_4;
        res_V_14_reg_1221 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_5;
        res_V_15_reg_1226 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_6;
        res_V_16_reg_1231 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_7;
        res_V_17_reg_1236 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_8;
        res_V_18_reg_1241 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_9;
        res_V_19_reg_1246 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_10;
        res_V_20_reg_1251 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_11;
        res_V_21_reg_1256 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_12;
        res_V_22_reg_1261 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_13;
        res_V_23_reg_1266 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_14;
        res_V_24_reg_1271 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_15;
        res_V_25_reg_1276 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_16;
        res_V_26_reg_1281 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_17;
        res_V_27_reg_1286 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_18;
        res_V_28_reg_1291 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_19;
        res_V_29_reg_1296 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_20;
        res_V_30_reg_1301 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_21;
        res_V_31_reg_1306 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_22;
        res_V_32_reg_1311 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_23;
        res_V_33_reg_1316 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_24;
        res_V_34_reg_1321 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_25;
        res_V_35_reg_1326 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_26;
        res_V_36_reg_1331 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_27;
        res_V_37_reg_1336 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_28;
        res_V_38_reg_1341 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_29;
        res_V_39_reg_1346 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_30;
        res_V_40_reg_1351 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_31;
        res_V_41_reg_1356 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_32;
        res_V_42_reg_1361 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_33;
        res_V_43_reg_1366 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_34;
        res_V_44_reg_1371 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_35;
        res_V_45_reg_1376 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_36;
        res_V_46_reg_1381 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_37;
        res_V_47_reg_1386 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_38;
        res_V_48_reg_1391 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_39;
        res_V_49_reg_1396 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_40;
        res_V_50_reg_1401 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_41;
        res_V_51_reg_1406 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_42;
        res_V_52_reg_1411 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_43;
        res_V_53_reg_1416 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_44;
        res_V_54_reg_1421 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_45;
        res_V_55_reg_1426 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_46;
        res_V_56_reg_1431 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_47;
        res_V_57_reg_1436 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_48;
        res_V_58_reg_1441 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_49;
        res_V_59_reg_1446 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_50;
        res_V_60_reg_1451 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_51;
        res_V_61_reg_1456 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_52;
        res_V_62_reg_1461 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_53;
        res_V_63_reg_1466 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_54;
        res_V_64_reg_1471 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_55;
        res_V_65_reg_1476 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_56;
        res_V_66_reg_1481 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_57;
        res_V_67_reg_1486 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_58;
        res_V_68_reg_1491 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_59;
        res_V_69_reg_1496 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_60;
        res_V_70_reg_1501 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_61;
        res_V_71_reg_1506 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_62;
        res_V_72_reg_1511 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_63;
        res_V_reg_1196 <= grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_return_0;
    end
end

always @ (*) begin
    if (((layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer19_out_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_blk_n = layer18_out_empty_n;
    end else begin
        layer18_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer18_out_read = 1'b1;
    end else begin
        layer18_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer19_out_blk_n = layer19_out_full_n;
    end else begin
        layer19_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer19_out_write = 1'b1;
    end else begin
        layer19_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((layer19_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((layer18_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign data_V_fu_247_p1 = layer18_out_dout[5:0];

assign grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start = grp_dense_wrapper_ap_ufixed_6_0_4_0_0_ap_fixed_16_6_5_3_0_config19_s_fu_201_ap_start_reg;

assign layer19_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{res_V_72_reg_1511}, {res_V_71_reg_1506}}, {res_V_70_reg_1501}}, {res_V_69_reg_1496}}, {res_V_68_reg_1491}}, {res_V_67_reg_1486}}, {res_V_66_reg_1481}}, {res_V_65_reg_1476}}, {res_V_64_reg_1471}}, {res_V_63_reg_1466}}, {res_V_62_reg_1461}}, {res_V_61_reg_1456}}, {res_V_60_reg_1451}}, {res_V_59_reg_1446}}, {res_V_58_reg_1441}}, {res_V_57_reg_1436}}, {res_V_56_reg_1431}}, {res_V_55_reg_1426}}, {res_V_54_reg_1421}}, {res_V_53_reg_1416}}, {res_V_52_reg_1411}}, {res_V_51_reg_1406}}, {res_V_50_reg_1401}}, {res_V_49_reg_1396}}, {res_V_48_reg_1391}}, {res_V_47_reg_1386}}, {res_V_46_reg_1381}}, {res_V_45_reg_1376}}, {res_V_44_reg_1371}}, {res_V_43_reg_1366}}, {res_V_42_reg_1361}}, {res_V_41_reg_1356}}, {res_V_40_reg_1351}}, {res_V_39_reg_1346}}, {res_V_38_reg_1341}}, {res_V_37_reg_1336}}, {res_V_36_reg_1331}}, {res_V_35_reg_1326}}, {res_V_34_reg_1321}}, {res_V_33_reg_1316}}, {res_V_32_reg_1311}}, {res_V_31_reg_1306}}, {res_V_30_reg_1301}}, {res_V_29_reg_1296}}, {res_V_28_reg_1291}}, {res_V_27_reg_1286}}, {res_V_26_reg_1281}}, {res_V_25_reg_1276}}, {res_V_24_reg_1271}}, {res_V_23_reg_1266}}, {res_V_22_reg_1261}}, {res_V_21_reg_1256}}, {res_V_20_reg_1251}}, {res_V_19_reg_1246}}, {res_V_18_reg_1241}}, {res_V_17_reg_1236}}, {res_V_16_reg_1231}}, {res_V_15_reg_1226}}, {res_V_14_reg_1221}}, {res_V_13_reg_1216}}, {res_V_12_reg_1211}}, {res_V_11_reg_1206}}, {res_V_10_reg_1201}}, {res_V_reg_1196}};

assign start_out = real_start;

endmodule //kernel_wrapper_dense_array_ap_ufixed_42u_array_ap_fixed_16_6_5_3_0_64u_config19_s
