// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module kernel_wrapper_relu_array_ap_fixed_16u_array_ap_ufixed_6_0_4_0_0_16u_relu_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_empty_n,
        layer6_out_read,
        layer8_out_din,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_full_n,
        layer8_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer6_out_dout;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [95:0] layer8_out_din;
input  [8:0] layer8_out_num_data_valid;
input  [8:0] layer8_out_fifo_cap;
input   layer8_out_full_n;
output   layer8_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer6_out_read;
reg layer8_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_303_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer8_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] out_data_data_16_fu_600_p3;
reg   [5:0] out_data_data_16_reg_2740;
wire   [5:0] out_data_data_18_fu_740_p3;
reg   [5:0] out_data_data_18_reg_2745;
wire   [5:0] out_data_data_20_fu_880_p3;
reg   [5:0] out_data_data_20_reg_2750;
wire   [5:0] out_data_data_22_fu_1020_p3;
reg   [5:0] out_data_data_22_reg_2755;
wire   [5:0] out_data_data_24_fu_1160_p3;
reg   [5:0] out_data_data_24_reg_2760;
wire   [5:0] out_data_data_26_fu_1300_p3;
reg   [5:0] out_data_data_26_reg_2765;
wire   [5:0] out_data_data_28_fu_1440_p3;
reg   [5:0] out_data_data_28_reg_2770;
wire   [5:0] out_data_data_30_fu_1580_p3;
reg   [5:0] out_data_data_30_reg_2775;
wire   [5:0] select_ln1649_fu_1720_p3;
reg   [5:0] select_ln1649_reg_2780;
wire   [5:0] select_ln1649_120_fu_1860_p3;
reg   [5:0] select_ln1649_120_reg_2785;
wire   [5:0] select_ln1649_121_fu_2000_p3;
reg   [5:0] select_ln1649_121_reg_2790;
wire   [5:0] select_ln1649_122_fu_2140_p3;
reg   [5:0] select_ln1649_122_reg_2795;
wire   [5:0] select_ln1649_123_fu_2280_p3;
reg   [5:0] select_ln1649_123_reg_2800;
wire   [5:0] select_ln1649_124_fu_2420_p3;
reg   [5:0] select_ln1649_124_reg_2805;
wire   [5:0] select_ln1649_125_fu_2560_p3;
reg   [5:0] select_ln1649_125_reg_2810;
wire   [5:0] select_ln1649_126_fu_2700_p3;
reg   [5:0] select_ln1649_126_reg_2815;
reg   [7:0] i_fu_278;
wire   [7:0] i_4_fu_309_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_3;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] in_data_data_fu_320_p1;
wire   [2:0] trunc_ln828_fu_506_p1;
wire   [0:0] p_Result_s_fu_490_p3;
wire   [0:0] r_fu_510_p2;
wire   [0:0] or_ln374_fu_524_p2;
wire   [0:0] p_Result_763_fu_498_p3;
wire   [0:0] and_ln374_fu_530_p2;
wire   [5:0] p_Val2_194_fu_480_p4;
wire   [5:0] zext_ln377_fu_536_p1;
wire   [5:0] tmp_s_fu_546_p4;
wire   [5:0] p_Val2_270_fu_540_p2;
wire   [0:0] tmp_650_fu_568_p3;
wire   [0:0] Range1_all_zeros_fu_562_p2;
wire   [0:0] Range1_all_ones_fu_556_p2;
wire   [0:0] p_Result_764_fu_516_p3;
wire   [0:0] select_ln888_fu_576_p3;
wire   [0:0] deleted_zeros_fu_584_p3;
wire   [0:0] icmp_ln1649_fu_474_p2;
wire   [5:0] out_data_data_fu_592_p3;
wire   [15:0] in_data_data_22_fu_344_p4;
wire   [2:0] tmp_252_fu_640_p4;
wire   [0:0] p_Result_720_fu_624_p3;
wire   [0:0] r_128_fu_650_p2;
wire   [0:0] or_ln374_128_fu_664_p2;
wire   [0:0] p_Result_765_fu_632_p3;
wire   [0:0] and_ln374_128_fu_670_p2;
wire   [5:0] p_Val2_195_fu_614_p4;
wire   [5:0] zext_ln377_128_fu_676_p1;
wire   [5:0] tmp_253_fu_686_p4;
wire   [5:0] p_Val2_272_fu_680_p2;
wire   [0:0] tmp_654_fu_708_p3;
wire   [0:0] Range1_all_zeros_128_fu_702_p2;
wire   [0:0] Range1_all_ones_128_fu_696_p2;
wire   [0:0] p_Result_766_fu_656_p3;
wire   [0:0] select_ln888_128_fu_716_p3;
wire   [0:0] deleted_zeros_128_fu_724_p3;
wire   [0:0] icmp_ln1649_128_fu_608_p2;
wire   [5:0] out_data_data_17_fu_732_p3;
wire   [15:0] in_data_data_23_fu_354_p4;
wire   [2:0] tmp_254_fu_780_p4;
wire   [0:0] p_Result_723_fu_764_p3;
wire   [0:0] r_129_fu_790_p2;
wire   [0:0] or_ln374_129_fu_804_p2;
wire   [0:0] p_Result_767_fu_772_p3;
wire   [0:0] and_ln374_129_fu_810_p2;
wire   [5:0] p_Val2_196_fu_754_p4;
wire   [5:0] zext_ln377_129_fu_816_p1;
wire   [5:0] tmp_255_fu_826_p4;
wire   [5:0] p_Val2_274_fu_820_p2;
wire   [0:0] tmp_658_fu_848_p3;
wire   [0:0] Range1_all_zeros_129_fu_842_p2;
wire   [0:0] Range1_all_ones_129_fu_836_p2;
wire   [0:0] p_Result_768_fu_796_p3;
wire   [0:0] select_ln888_129_fu_856_p3;
wire   [0:0] deleted_zeros_129_fu_864_p3;
wire   [0:0] icmp_ln1649_129_fu_748_p2;
wire   [5:0] out_data_data_19_fu_872_p3;
wire   [15:0] in_data_data_24_fu_364_p4;
wire   [2:0] tmp_256_fu_920_p4;
wire   [0:0] p_Result_726_fu_904_p3;
wire   [0:0] r_130_fu_930_p2;
wire   [0:0] or_ln374_130_fu_944_p2;
wire   [0:0] p_Result_769_fu_912_p3;
wire   [0:0] and_ln374_130_fu_950_p2;
wire   [5:0] p_Val2_197_fu_894_p4;
wire   [5:0] zext_ln377_130_fu_956_p1;
wire   [5:0] tmp_257_fu_966_p4;
wire   [5:0] p_Val2_276_fu_960_p2;
wire   [0:0] tmp_662_fu_988_p3;
wire   [0:0] Range1_all_zeros_130_fu_982_p2;
wire   [0:0] Range1_all_ones_130_fu_976_p2;
wire   [0:0] p_Result_770_fu_936_p3;
wire   [0:0] select_ln888_130_fu_996_p3;
wire   [0:0] deleted_zeros_130_fu_1004_p3;
wire   [0:0] icmp_ln1649_130_fu_888_p2;
wire   [5:0] out_data_data_21_fu_1012_p3;
wire   [15:0] p_Val2_193_fu_374_p4;
wire   [2:0] tmp_fu_1060_p4;
wire   [0:0] p_Result_729_fu_1044_p3;
wire   [0:0] r_131_fu_1070_p2;
wire   [0:0] or_ln374_131_fu_1084_p2;
wire   [0:0] p_Result_771_fu_1052_p3;
wire   [0:0] and_ln374_131_fu_1090_p2;
wire   [5:0] p_Val2_198_fu_1034_p4;
wire   [5:0] zext_ln377_131_fu_1096_p1;
wire   [5:0] tmp_258_fu_1106_p4;
wire   [5:0] p_Val2_277_fu_1100_p2;
wire   [0:0] tmp_666_fu_1128_p3;
wire   [0:0] Range1_all_zeros_131_fu_1122_p2;
wire   [0:0] Range1_all_ones_131_fu_1116_p2;
wire   [0:0] p_Result_772_fu_1076_p3;
wire   [0:0] select_ln888_131_fu_1136_p3;
wire   [0:0] deleted_zeros_131_fu_1144_p3;
wire   [0:0] icmp_ln1649_131_fu_1028_p2;
wire   [5:0] out_data_data_23_fu_1152_p3;
wire   [15:0] p_Val2_112_fu_384_p4;
wire   [2:0] tmp_259_fu_1200_p4;
wire   [0:0] p_Result_732_fu_1184_p3;
wire   [0:0] r_132_fu_1210_p2;
wire   [0:0] or_ln374_132_fu_1224_p2;
wire   [0:0] p_Result_773_fu_1192_p3;
wire   [0:0] and_ln374_132_fu_1230_p2;
wire   [5:0] p_Val2_199_fu_1174_p4;
wire   [5:0] zext_ln377_132_fu_1236_p1;
wire   [5:0] tmp_260_fu_1246_p4;
wire   [5:0] p_Val2_278_fu_1240_p2;
wire   [0:0] tmp_670_fu_1268_p3;
wire   [0:0] Range1_all_zeros_132_fu_1262_p2;
wire   [0:0] Range1_all_ones_132_fu_1256_p2;
wire   [0:0] p_Result_774_fu_1216_p3;
wire   [0:0] select_ln888_132_fu_1276_p3;
wire   [0:0] deleted_zeros_132_fu_1284_p3;
wire   [0:0] icmp_ln1649_132_fu_1168_p2;
wire   [5:0] out_data_data_25_fu_1292_p3;
wire   [15:0] p_Val2_113_fu_394_p4;
wire   [2:0] tmp_261_fu_1340_p4;
wire   [0:0] p_Result_735_fu_1324_p3;
wire   [0:0] r_133_fu_1350_p2;
wire   [0:0] or_ln374_133_fu_1364_p2;
wire   [0:0] p_Result_775_fu_1332_p3;
wire   [0:0] and_ln374_133_fu_1370_p2;
wire   [5:0] p_Val2_200_fu_1314_p4;
wire   [5:0] zext_ln377_133_fu_1376_p1;
wire   [5:0] tmp_262_fu_1386_p4;
wire   [5:0] p_Val2_279_fu_1380_p2;
wire   [0:0] tmp_674_fu_1408_p3;
wire   [0:0] Range1_all_zeros_133_fu_1402_p2;
wire   [0:0] Range1_all_ones_133_fu_1396_p2;
wire   [0:0] p_Result_776_fu_1356_p3;
wire   [0:0] select_ln888_133_fu_1416_p3;
wire   [0:0] deleted_zeros_133_fu_1424_p3;
wire   [0:0] icmp_ln1649_133_fu_1308_p2;
wire   [5:0] out_data_data_27_fu_1432_p3;
wire   [15:0] p_Val2_114_fu_404_p4;
wire   [2:0] tmp_263_fu_1480_p4;
wire   [0:0] p_Result_738_fu_1464_p3;
wire   [0:0] r_134_fu_1490_p2;
wire   [0:0] or_ln374_134_fu_1504_p2;
wire   [0:0] p_Result_777_fu_1472_p3;
wire   [0:0] and_ln374_134_fu_1510_p2;
wire   [5:0] p_Val2_201_fu_1454_p4;
wire   [5:0] zext_ln377_134_fu_1516_p1;
wire   [5:0] tmp_264_fu_1526_p4;
wire   [5:0] p_Val2_280_fu_1520_p2;
wire   [0:0] tmp_678_fu_1548_p3;
wire   [0:0] Range1_all_zeros_134_fu_1542_p2;
wire   [0:0] Range1_all_ones_134_fu_1536_p2;
wire   [0:0] p_Result_778_fu_1496_p3;
wire   [0:0] select_ln888_134_fu_1556_p3;
wire   [0:0] deleted_zeros_134_fu_1564_p3;
wire   [0:0] icmp_ln1649_134_fu_1448_p2;
wire   [5:0] out_data_data_29_fu_1572_p3;
wire   [15:0] p_Val2_115_fu_414_p4;
wire   [2:0] tmp_265_fu_1620_p4;
wire   [0:0] p_Result_741_fu_1604_p3;
wire   [0:0] r_135_fu_1630_p2;
wire   [0:0] or_ln374_135_fu_1644_p2;
wire   [0:0] p_Result_779_fu_1612_p3;
wire   [0:0] and_ln374_135_fu_1650_p2;
wire   [5:0] p_Val2_202_fu_1594_p4;
wire   [5:0] zext_ln377_135_fu_1656_p1;
wire   [5:0] tmp_266_fu_1666_p4;
wire   [5:0] p_Val2_281_fu_1660_p2;
wire   [0:0] tmp_682_fu_1688_p3;
wire   [0:0] Range1_all_zeros_135_fu_1682_p2;
wire   [0:0] Range1_all_ones_135_fu_1676_p2;
wire   [0:0] p_Result_780_fu_1636_p3;
wire   [0:0] select_ln888_135_fu_1696_p3;
wire   [0:0] deleted_zeros_135_fu_1704_p3;
wire   [0:0] icmp_ln1649_135_fu_1588_p2;
wire   [5:0] select_ln302_fu_1712_p3;
wire   [15:0] p_Val2_116_fu_424_p4;
wire   [2:0] tmp_267_fu_1760_p4;
wire   [0:0] p_Result_744_fu_1744_p3;
wire   [0:0] r_136_fu_1770_p2;
wire   [0:0] or_ln374_136_fu_1784_p2;
wire   [0:0] p_Result_781_fu_1752_p3;
wire   [0:0] and_ln374_136_fu_1790_p2;
wire   [5:0] p_Val2_203_fu_1734_p4;
wire   [5:0] zext_ln377_136_fu_1796_p1;
wire   [5:0] tmp_268_fu_1806_p4;
wire   [5:0] p_Val2_282_fu_1800_p2;
wire   [0:0] tmp_686_fu_1828_p3;
wire   [0:0] Range1_all_zeros_136_fu_1822_p2;
wire   [0:0] Range1_all_ones_136_fu_1816_p2;
wire   [0:0] p_Result_782_fu_1776_p3;
wire   [0:0] select_ln888_136_fu_1836_p3;
wire   [0:0] deleted_zeros_136_fu_1844_p3;
wire   [0:0] icmp_ln1649_136_fu_1728_p2;
wire   [5:0] select_ln302_120_fu_1852_p3;
wire   [15:0] p_Val2_117_fu_434_p4;
wire   [2:0] tmp_269_fu_1900_p4;
wire   [0:0] p_Result_747_fu_1884_p3;
wire   [0:0] r_137_fu_1910_p2;
wire   [0:0] or_ln374_137_fu_1924_p2;
wire   [0:0] p_Result_783_fu_1892_p3;
wire   [0:0] and_ln374_137_fu_1930_p2;
wire   [5:0] p_Val2_204_fu_1874_p4;
wire   [5:0] zext_ln377_137_fu_1936_p1;
wire   [5:0] tmp_270_fu_1946_p4;
wire   [5:0] p_Val2_283_fu_1940_p2;
wire   [0:0] tmp_690_fu_1968_p3;
wire   [0:0] Range1_all_zeros_137_fu_1962_p2;
wire   [0:0] Range1_all_ones_137_fu_1956_p2;
wire   [0:0] p_Result_784_fu_1916_p3;
wire   [0:0] select_ln888_137_fu_1976_p3;
wire   [0:0] deleted_zeros_137_fu_1984_p3;
wire   [0:0] icmp_ln1649_137_fu_1868_p2;
wire   [5:0] select_ln302_121_fu_1992_p3;
wire   [15:0] p_Val2_118_fu_444_p4;
wire   [2:0] tmp_271_fu_2040_p4;
wire   [0:0] p_Result_750_fu_2024_p3;
wire   [0:0] r_138_fu_2050_p2;
wire   [0:0] or_ln374_138_fu_2064_p2;
wire   [0:0] p_Result_785_fu_2032_p3;
wire   [0:0] and_ln374_138_fu_2070_p2;
wire   [5:0] p_Val2_205_fu_2014_p4;
wire   [5:0] zext_ln377_138_fu_2076_p1;
wire   [5:0] tmp_272_fu_2086_p4;
wire   [5:0] p_Val2_284_fu_2080_p2;
wire   [0:0] tmp_694_fu_2108_p3;
wire   [0:0] Range1_all_zeros_138_fu_2102_p2;
wire   [0:0] Range1_all_ones_138_fu_2096_p2;
wire   [0:0] p_Result_786_fu_2056_p3;
wire   [0:0] select_ln888_138_fu_2116_p3;
wire   [0:0] deleted_zeros_138_fu_2124_p3;
wire   [0:0] icmp_ln1649_138_fu_2008_p2;
wire   [5:0] select_ln302_122_fu_2132_p3;
wire   [15:0] p_Val2_119_fu_454_p4;
wire   [2:0] tmp_273_fu_2180_p4;
wire   [0:0] p_Result_753_fu_2164_p3;
wire   [0:0] r_139_fu_2190_p2;
wire   [0:0] or_ln374_139_fu_2204_p2;
wire   [0:0] p_Result_787_fu_2172_p3;
wire   [0:0] and_ln374_139_fu_2210_p2;
wire   [5:0] p_Val2_206_fu_2154_p4;
wire   [5:0] zext_ln377_139_fu_2216_p1;
wire   [5:0] tmp_274_fu_2226_p4;
wire   [5:0] p_Val2_285_fu_2220_p2;
wire   [0:0] tmp_698_fu_2248_p3;
wire   [0:0] Range1_all_zeros_139_fu_2242_p2;
wire   [0:0] Range1_all_ones_139_fu_2236_p2;
wire   [0:0] p_Result_788_fu_2196_p3;
wire   [0:0] select_ln888_139_fu_2256_p3;
wire   [0:0] deleted_zeros_139_fu_2264_p3;
wire   [0:0] icmp_ln1649_139_fu_2148_p2;
wire   [5:0] select_ln302_123_fu_2272_p3;
wire   [15:0] p_Val2_120_fu_464_p4;
wire   [2:0] tmp_275_fu_2320_p4;
wire   [0:0] p_Result_756_fu_2304_p3;
wire   [0:0] r_140_fu_2330_p2;
wire   [0:0] or_ln374_140_fu_2344_p2;
wire   [0:0] p_Result_789_fu_2312_p3;
wire   [0:0] and_ln374_140_fu_2350_p2;
wire   [5:0] p_Val2_207_fu_2294_p4;
wire   [5:0] zext_ln377_140_fu_2356_p1;
wire   [5:0] tmp_276_fu_2366_p4;
wire   [5:0] p_Val2_286_fu_2360_p2;
wire   [0:0] tmp_702_fu_2388_p3;
wire   [0:0] Range1_all_zeros_140_fu_2382_p2;
wire   [0:0] Range1_all_ones_140_fu_2376_p2;
wire   [0:0] p_Result_790_fu_2336_p3;
wire   [0:0] select_ln888_140_fu_2396_p3;
wire   [0:0] deleted_zeros_140_fu_2404_p3;
wire   [0:0] icmp_ln1649_140_fu_2288_p2;
wire   [5:0] select_ln302_124_fu_2412_p3;
wire   [15:0] p_Val2_287_fu_324_p4;
wire   [2:0] tmp_277_fu_2460_p4;
wire   [0:0] p_Result_759_fu_2444_p3;
wire   [0:0] r_141_fu_2470_p2;
wire   [0:0] or_ln374_141_fu_2484_p2;
wire   [0:0] p_Result_791_fu_2452_p3;
wire   [0:0] and_ln374_141_fu_2490_p2;
wire   [5:0] p_Val2_288_fu_2434_p4;
wire   [5:0] zext_ln377_141_fu_2496_p1;
wire   [5:0] tmp_278_fu_2506_p4;
wire   [5:0] p_Val2_289_fu_2500_p2;
wire   [0:0] tmp_706_fu_2528_p3;
wire   [0:0] Range1_all_zeros_141_fu_2522_p2;
wire   [0:0] Range1_all_ones_141_fu_2516_p2;
wire   [0:0] p_Result_792_fu_2476_p3;
wire   [0:0] select_ln888_141_fu_2536_p3;
wire   [0:0] deleted_zeros_141_fu_2544_p3;
wire   [0:0] icmp_ln1649_141_fu_2428_p2;
wire   [5:0] select_ln302_125_fu_2552_p3;
wire   [15:0] p_Val2_192_fu_334_p4;
wire   [2:0] tmp_279_fu_2600_p4;
wire   [0:0] p_Result_762_fu_2584_p3;
wire   [0:0] r_142_fu_2610_p2;
wire   [0:0] or_ln374_142_fu_2624_p2;
wire   [0:0] p_Result_793_fu_2592_p3;
wire   [0:0] and_ln374_142_fu_2630_p2;
wire   [5:0] p_Val2_290_fu_2574_p4;
wire   [5:0] zext_ln377_142_fu_2636_p1;
wire   [5:0] tmp_280_fu_2646_p4;
wire   [5:0] p_Val2_291_fu_2640_p2;
wire   [0:0] tmp_710_fu_2668_p3;
wire   [0:0] Range1_all_zeros_142_fu_2662_p2;
wire   [0:0] Range1_all_ones_142_fu_2656_p2;
wire   [0:0] p_Result_794_fu_2616_p3;
wire   [0:0] select_ln888_142_fu_2676_p3;
wire   [0:0] deleted_zeros_142_fu_2684_p3;
wire   [0:0] icmp_ln1649_142_fu_2568_p2;
wire   [5:0] select_ln302_126_fu_2692_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_142;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

kernel_wrapper_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_142)) begin
        if ((icmp_ln41_fu_303_p2 == 1'd0)) begin
            i_fu_278 <= i_4_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_278 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        out_data_data_16_reg_2740 <= out_data_data_16_fu_600_p3;
        out_data_data_18_reg_2745 <= out_data_data_18_fu_740_p3;
        out_data_data_20_reg_2750 <= out_data_data_20_fu_880_p3;
        out_data_data_22_reg_2755 <= out_data_data_22_fu_1020_p3;
        out_data_data_24_reg_2760 <= out_data_data_24_fu_1160_p3;
        out_data_data_26_reg_2765 <= out_data_data_26_fu_1300_p3;
        out_data_data_28_reg_2770 <= out_data_data_28_fu_1440_p3;
        out_data_data_30_reg_2775 <= out_data_data_30_fu_1580_p3;
        select_ln1649_120_reg_2785 <= select_ln1649_120_fu_1860_p3;
        select_ln1649_121_reg_2790 <= select_ln1649_121_fu_2000_p3;
        select_ln1649_122_reg_2795 <= select_ln1649_122_fu_2140_p3;
        select_ln1649_123_reg_2800 <= select_ln1649_123_fu_2280_p3;
        select_ln1649_124_reg_2805 <= select_ln1649_124_fu_2420_p3;
        select_ln1649_125_reg_2810 <= select_ln1649_125_fu_2560_p3;
        select_ln1649_126_reg_2815 <= select_ln1649_126_fu_2700_p3;
        select_ln1649_reg_2780 <= select_ln1649_fu_1720_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_303_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_278;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_128_fu_696_p2 = ((tmp_253_fu_686_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_129_fu_836_p2 = ((tmp_255_fu_826_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_130_fu_976_p2 = ((tmp_257_fu_966_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_131_fu_1116_p2 = ((tmp_258_fu_1106_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_132_fu_1256_p2 = ((tmp_260_fu_1246_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_133_fu_1396_p2 = ((tmp_262_fu_1386_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_134_fu_1536_p2 = ((tmp_264_fu_1526_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_135_fu_1676_p2 = ((tmp_266_fu_1666_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_136_fu_1816_p2 = ((tmp_268_fu_1806_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_137_fu_1956_p2 = ((tmp_270_fu_1946_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_138_fu_2096_p2 = ((tmp_272_fu_2086_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_139_fu_2236_p2 = ((tmp_274_fu_2226_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_140_fu_2376_p2 = ((tmp_276_fu_2366_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_141_fu_2516_p2 = ((tmp_278_fu_2506_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_142_fu_2656_p2 = ((tmp_280_fu_2646_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_ones_fu_556_p2 = ((tmp_s_fu_546_p4 == 6'd63) ? 1'b1 : 1'b0);

assign Range1_all_zeros_128_fu_702_p2 = ((tmp_253_fu_686_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_129_fu_842_p2 = ((tmp_255_fu_826_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_130_fu_982_p2 = ((tmp_257_fu_966_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_131_fu_1122_p2 = ((tmp_258_fu_1106_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_132_fu_1262_p2 = ((tmp_260_fu_1246_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_133_fu_1402_p2 = ((tmp_262_fu_1386_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_134_fu_1542_p2 = ((tmp_264_fu_1526_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_135_fu_1682_p2 = ((tmp_266_fu_1666_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_136_fu_1822_p2 = ((tmp_268_fu_1806_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_137_fu_1962_p2 = ((tmp_270_fu_1946_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_138_fu_2102_p2 = ((tmp_272_fu_2086_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_139_fu_2242_p2 = ((tmp_274_fu_2226_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_140_fu_2382_p2 = ((tmp_276_fu_2366_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_141_fu_2522_p2 = ((tmp_278_fu_2506_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_142_fu_2662_p2 = ((tmp_280_fu_2646_p4 == 6'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_562_p2 = ((tmp_s_fu_546_p4 == 6'd0) ? 1'b1 : 1'b0);

assign and_ln374_128_fu_670_p2 = (p_Result_765_fu_632_p3 & or_ln374_128_fu_664_p2);

assign and_ln374_129_fu_810_p2 = (p_Result_767_fu_772_p3 & or_ln374_129_fu_804_p2);

assign and_ln374_130_fu_950_p2 = (p_Result_769_fu_912_p3 & or_ln374_130_fu_944_p2);

assign and_ln374_131_fu_1090_p2 = (p_Result_771_fu_1052_p3 & or_ln374_131_fu_1084_p2);

assign and_ln374_132_fu_1230_p2 = (p_Result_773_fu_1192_p3 & or_ln374_132_fu_1224_p2);

assign and_ln374_133_fu_1370_p2 = (p_Result_775_fu_1332_p3 & or_ln374_133_fu_1364_p2);

assign and_ln374_134_fu_1510_p2 = (p_Result_777_fu_1472_p3 & or_ln374_134_fu_1504_p2);

assign and_ln374_135_fu_1650_p2 = (p_Result_779_fu_1612_p3 & or_ln374_135_fu_1644_p2);

assign and_ln374_136_fu_1790_p2 = (p_Result_781_fu_1752_p3 & or_ln374_136_fu_1784_p2);

assign and_ln374_137_fu_1930_p2 = (p_Result_783_fu_1892_p3 & or_ln374_137_fu_1924_p2);

assign and_ln374_138_fu_2070_p2 = (p_Result_785_fu_2032_p3 & or_ln374_138_fu_2064_p2);

assign and_ln374_139_fu_2210_p2 = (p_Result_787_fu_2172_p3 & or_ln374_139_fu_2204_p2);

assign and_ln374_140_fu_2350_p2 = (p_Result_789_fu_2312_p3 & or_ln374_140_fu_2344_p2);

assign and_ln374_141_fu_2490_p2 = (p_Result_791_fu_2452_p3 & or_ln374_141_fu_2484_p2);

assign and_ln374_142_fu_2630_p2 = (p_Result_793_fu_2592_p3 & or_ln374_142_fu_2624_p2);

assign and_ln374_fu_530_p2 = (p_Result_763_fu_498_p3 & or_ln374_fu_524_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer6_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer8_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_142 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign deleted_zeros_128_fu_724_p3 = ((p_Result_766_fu_656_p3[0:0] == 1'b1) ? select_ln888_128_fu_716_p3 : Range1_all_zeros_128_fu_702_p2);

assign deleted_zeros_129_fu_864_p3 = ((p_Result_768_fu_796_p3[0:0] == 1'b1) ? select_ln888_129_fu_856_p3 : Range1_all_zeros_129_fu_842_p2);

assign deleted_zeros_130_fu_1004_p3 = ((p_Result_770_fu_936_p3[0:0] == 1'b1) ? select_ln888_130_fu_996_p3 : Range1_all_zeros_130_fu_982_p2);

assign deleted_zeros_131_fu_1144_p3 = ((p_Result_772_fu_1076_p3[0:0] == 1'b1) ? select_ln888_131_fu_1136_p3 : Range1_all_zeros_131_fu_1122_p2);

assign deleted_zeros_132_fu_1284_p3 = ((p_Result_774_fu_1216_p3[0:0] == 1'b1) ? select_ln888_132_fu_1276_p3 : Range1_all_zeros_132_fu_1262_p2);

assign deleted_zeros_133_fu_1424_p3 = ((p_Result_776_fu_1356_p3[0:0] == 1'b1) ? select_ln888_133_fu_1416_p3 : Range1_all_zeros_133_fu_1402_p2);

assign deleted_zeros_134_fu_1564_p3 = ((p_Result_778_fu_1496_p3[0:0] == 1'b1) ? select_ln888_134_fu_1556_p3 : Range1_all_zeros_134_fu_1542_p2);

assign deleted_zeros_135_fu_1704_p3 = ((p_Result_780_fu_1636_p3[0:0] == 1'b1) ? select_ln888_135_fu_1696_p3 : Range1_all_zeros_135_fu_1682_p2);

assign deleted_zeros_136_fu_1844_p3 = ((p_Result_782_fu_1776_p3[0:0] == 1'b1) ? select_ln888_136_fu_1836_p3 : Range1_all_zeros_136_fu_1822_p2);

assign deleted_zeros_137_fu_1984_p3 = ((p_Result_784_fu_1916_p3[0:0] == 1'b1) ? select_ln888_137_fu_1976_p3 : Range1_all_zeros_137_fu_1962_p2);

assign deleted_zeros_138_fu_2124_p3 = ((p_Result_786_fu_2056_p3[0:0] == 1'b1) ? select_ln888_138_fu_2116_p3 : Range1_all_zeros_138_fu_2102_p2);

assign deleted_zeros_139_fu_2264_p3 = ((p_Result_788_fu_2196_p3[0:0] == 1'b1) ? select_ln888_139_fu_2256_p3 : Range1_all_zeros_139_fu_2242_p2);

assign deleted_zeros_140_fu_2404_p3 = ((p_Result_790_fu_2336_p3[0:0] == 1'b1) ? select_ln888_140_fu_2396_p3 : Range1_all_zeros_140_fu_2382_p2);

assign deleted_zeros_141_fu_2544_p3 = ((p_Result_792_fu_2476_p3[0:0] == 1'b1) ? select_ln888_141_fu_2536_p3 : Range1_all_zeros_141_fu_2522_p2);

assign deleted_zeros_142_fu_2684_p3 = ((p_Result_794_fu_2616_p3[0:0] == 1'b1) ? select_ln888_142_fu_2676_p3 : Range1_all_zeros_142_fu_2662_p2);

assign deleted_zeros_fu_584_p3 = ((p_Result_764_fu_516_p3[0:0] == 1'b1) ? select_ln888_fu_576_p3 : Range1_all_zeros_fu_562_p2);

assign i_4_fu_309_p2 = (ap_sig_allocacmp_i_3 + 8'd1);

assign icmp_ln1649_128_fu_608_p2 = (($signed(in_data_data_22_fu_344_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_129_fu_748_p2 = (($signed(in_data_data_23_fu_354_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_130_fu_888_p2 = (($signed(in_data_data_24_fu_364_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_131_fu_1028_p2 = (($signed(p_Val2_193_fu_374_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_132_fu_1168_p2 = (($signed(p_Val2_112_fu_384_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_133_fu_1308_p2 = (($signed(p_Val2_113_fu_394_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_134_fu_1448_p2 = (($signed(p_Val2_114_fu_404_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_135_fu_1588_p2 = (($signed(p_Val2_115_fu_414_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_136_fu_1728_p2 = (($signed(p_Val2_116_fu_424_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_137_fu_1868_p2 = (($signed(p_Val2_117_fu_434_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_138_fu_2008_p2 = (($signed(p_Val2_118_fu_444_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_139_fu_2148_p2 = (($signed(p_Val2_119_fu_454_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_140_fu_2288_p2 = (($signed(p_Val2_120_fu_464_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_141_fu_2428_p2 = (($signed(p_Val2_287_fu_324_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_142_fu_2568_p2 = (($signed(p_Val2_192_fu_334_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_474_p2 = (($signed(in_data_data_fu_320_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_303_p2 = ((ap_sig_allocacmp_i_3 == 8'd169) ? 1'b1 : 1'b0);

assign in_data_data_22_fu_344_p4 = {{layer6_out_dout[31:16]}};

assign in_data_data_23_fu_354_p4 = {{layer6_out_dout[47:32]}};

assign in_data_data_24_fu_364_p4 = {{layer6_out_dout[63:48]}};

assign in_data_data_fu_320_p1 = layer6_out_dout[15:0];

assign layer8_out_din = {{{{{{{{{{{{{{{{select_ln1649_126_reg_2815}, {select_ln1649_125_reg_2810}}, {select_ln1649_124_reg_2805}}, {select_ln1649_123_reg_2800}}, {select_ln1649_122_reg_2795}}, {select_ln1649_121_reg_2790}}, {select_ln1649_120_reg_2785}}, {select_ln1649_reg_2780}}, {out_data_data_30_reg_2775}}, {out_data_data_28_reg_2770}}, {out_data_data_26_reg_2765}}, {out_data_data_24_reg_2760}}, {out_data_data_22_reg_2755}}, {out_data_data_20_reg_2750}}, {out_data_data_18_reg_2745}}, {out_data_data_16_reg_2740}};

assign or_ln374_128_fu_664_p2 = (r_128_fu_650_p2 | p_Result_720_fu_624_p3);

assign or_ln374_129_fu_804_p2 = (r_129_fu_790_p2 | p_Result_723_fu_764_p3);

assign or_ln374_130_fu_944_p2 = (r_130_fu_930_p2 | p_Result_726_fu_904_p3);

assign or_ln374_131_fu_1084_p2 = (r_131_fu_1070_p2 | p_Result_729_fu_1044_p3);

assign or_ln374_132_fu_1224_p2 = (r_132_fu_1210_p2 | p_Result_732_fu_1184_p3);

assign or_ln374_133_fu_1364_p2 = (r_133_fu_1350_p2 | p_Result_735_fu_1324_p3);

assign or_ln374_134_fu_1504_p2 = (r_134_fu_1490_p2 | p_Result_738_fu_1464_p3);

assign or_ln374_135_fu_1644_p2 = (r_135_fu_1630_p2 | p_Result_741_fu_1604_p3);

assign or_ln374_136_fu_1784_p2 = (r_136_fu_1770_p2 | p_Result_744_fu_1744_p3);

assign or_ln374_137_fu_1924_p2 = (r_137_fu_1910_p2 | p_Result_747_fu_1884_p3);

assign or_ln374_138_fu_2064_p2 = (r_138_fu_2050_p2 | p_Result_750_fu_2024_p3);

assign or_ln374_139_fu_2204_p2 = (r_139_fu_2190_p2 | p_Result_753_fu_2164_p3);

assign or_ln374_140_fu_2344_p2 = (r_140_fu_2330_p2 | p_Result_756_fu_2304_p3);

assign or_ln374_141_fu_2484_p2 = (r_141_fu_2470_p2 | p_Result_759_fu_2444_p3);

assign or_ln374_142_fu_2624_p2 = (r_142_fu_2610_p2 | p_Result_762_fu_2584_p3);

assign or_ln374_fu_524_p2 = (r_fu_510_p2 | p_Result_s_fu_490_p3);

assign out_data_data_16_fu_600_p3 = ((icmp_ln1649_fu_474_p2[0:0] == 1'b1) ? out_data_data_fu_592_p3 : 6'd0);

assign out_data_data_17_fu_732_p3 = ((deleted_zeros_128_fu_724_p3[0:0] == 1'b1) ? p_Val2_272_fu_680_p2 : 6'd63);

assign out_data_data_18_fu_740_p3 = ((icmp_ln1649_128_fu_608_p2[0:0] == 1'b1) ? out_data_data_17_fu_732_p3 : 6'd0);

assign out_data_data_19_fu_872_p3 = ((deleted_zeros_129_fu_864_p3[0:0] == 1'b1) ? p_Val2_274_fu_820_p2 : 6'd63);

assign out_data_data_20_fu_880_p3 = ((icmp_ln1649_129_fu_748_p2[0:0] == 1'b1) ? out_data_data_19_fu_872_p3 : 6'd0);

assign out_data_data_21_fu_1012_p3 = ((deleted_zeros_130_fu_1004_p3[0:0] == 1'b1) ? p_Val2_276_fu_960_p2 : 6'd63);

assign out_data_data_22_fu_1020_p3 = ((icmp_ln1649_130_fu_888_p2[0:0] == 1'b1) ? out_data_data_21_fu_1012_p3 : 6'd0);

assign out_data_data_23_fu_1152_p3 = ((deleted_zeros_131_fu_1144_p3[0:0] == 1'b1) ? p_Val2_277_fu_1100_p2 : 6'd63);

assign out_data_data_24_fu_1160_p3 = ((icmp_ln1649_131_fu_1028_p2[0:0] == 1'b1) ? out_data_data_23_fu_1152_p3 : 6'd0);

assign out_data_data_25_fu_1292_p3 = ((deleted_zeros_132_fu_1284_p3[0:0] == 1'b1) ? p_Val2_278_fu_1240_p2 : 6'd63);

assign out_data_data_26_fu_1300_p3 = ((icmp_ln1649_132_fu_1168_p2[0:0] == 1'b1) ? out_data_data_25_fu_1292_p3 : 6'd0);

assign out_data_data_27_fu_1432_p3 = ((deleted_zeros_133_fu_1424_p3[0:0] == 1'b1) ? p_Val2_279_fu_1380_p2 : 6'd63);

assign out_data_data_28_fu_1440_p3 = ((icmp_ln1649_133_fu_1308_p2[0:0] == 1'b1) ? out_data_data_27_fu_1432_p3 : 6'd0);

assign out_data_data_29_fu_1572_p3 = ((deleted_zeros_134_fu_1564_p3[0:0] == 1'b1) ? p_Val2_280_fu_1520_p2 : 6'd63);

assign out_data_data_30_fu_1580_p3 = ((icmp_ln1649_134_fu_1448_p2[0:0] == 1'b1) ? out_data_data_29_fu_1572_p3 : 6'd0);

assign out_data_data_fu_592_p3 = ((deleted_zeros_fu_584_p3[0:0] == 1'b1) ? p_Val2_270_fu_540_p2 : 6'd63);

assign p_Result_720_fu_624_p3 = layer6_out_dout[32'd20];

assign p_Result_723_fu_764_p3 = layer6_out_dout[32'd36];

assign p_Result_726_fu_904_p3 = layer6_out_dout[32'd52];

assign p_Result_729_fu_1044_p3 = layer6_out_dout[32'd68];

assign p_Result_732_fu_1184_p3 = layer6_out_dout[32'd84];

assign p_Result_735_fu_1324_p3 = layer6_out_dout[32'd100];

assign p_Result_738_fu_1464_p3 = layer6_out_dout[32'd116];

assign p_Result_741_fu_1604_p3 = layer6_out_dout[32'd132];

assign p_Result_744_fu_1744_p3 = layer6_out_dout[32'd148];

assign p_Result_747_fu_1884_p3 = layer6_out_dout[32'd164];

assign p_Result_750_fu_2024_p3 = layer6_out_dout[32'd180];

assign p_Result_753_fu_2164_p3 = layer6_out_dout[32'd196];

assign p_Result_756_fu_2304_p3 = layer6_out_dout[32'd212];

assign p_Result_759_fu_2444_p3 = layer6_out_dout[32'd228];

assign p_Result_762_fu_2584_p3 = layer6_out_dout[32'd244];

assign p_Result_763_fu_498_p3 = layer6_out_dout[32'd3];

assign p_Result_764_fu_516_p3 = layer6_out_dout[32'd9];

assign p_Result_765_fu_632_p3 = layer6_out_dout[32'd19];

assign p_Result_766_fu_656_p3 = layer6_out_dout[32'd25];

assign p_Result_767_fu_772_p3 = layer6_out_dout[32'd35];

assign p_Result_768_fu_796_p3 = layer6_out_dout[32'd41];

assign p_Result_769_fu_912_p3 = layer6_out_dout[32'd51];

assign p_Result_770_fu_936_p3 = layer6_out_dout[32'd57];

assign p_Result_771_fu_1052_p3 = layer6_out_dout[32'd67];

assign p_Result_772_fu_1076_p3 = layer6_out_dout[32'd73];

assign p_Result_773_fu_1192_p3 = layer6_out_dout[32'd83];

assign p_Result_774_fu_1216_p3 = layer6_out_dout[32'd89];

assign p_Result_775_fu_1332_p3 = layer6_out_dout[32'd99];

assign p_Result_776_fu_1356_p3 = layer6_out_dout[32'd105];

assign p_Result_777_fu_1472_p3 = layer6_out_dout[32'd115];

assign p_Result_778_fu_1496_p3 = layer6_out_dout[32'd121];

assign p_Result_779_fu_1612_p3 = layer6_out_dout[32'd131];

assign p_Result_780_fu_1636_p3 = layer6_out_dout[32'd137];

assign p_Result_781_fu_1752_p3 = layer6_out_dout[32'd147];

assign p_Result_782_fu_1776_p3 = layer6_out_dout[32'd153];

assign p_Result_783_fu_1892_p3 = layer6_out_dout[32'd163];

assign p_Result_784_fu_1916_p3 = layer6_out_dout[32'd169];

assign p_Result_785_fu_2032_p3 = layer6_out_dout[32'd179];

assign p_Result_786_fu_2056_p3 = layer6_out_dout[32'd185];

assign p_Result_787_fu_2172_p3 = layer6_out_dout[32'd195];

assign p_Result_788_fu_2196_p3 = layer6_out_dout[32'd201];

assign p_Result_789_fu_2312_p3 = layer6_out_dout[32'd211];

assign p_Result_790_fu_2336_p3 = layer6_out_dout[32'd217];

assign p_Result_791_fu_2452_p3 = layer6_out_dout[32'd227];

assign p_Result_792_fu_2476_p3 = layer6_out_dout[32'd233];

assign p_Result_793_fu_2592_p3 = layer6_out_dout[32'd243];

assign p_Result_794_fu_2616_p3 = layer6_out_dout[32'd249];

assign p_Result_s_fu_490_p3 = layer6_out_dout[32'd4];

assign p_Val2_112_fu_384_p4 = {{layer6_out_dout[95:80]}};

assign p_Val2_113_fu_394_p4 = {{layer6_out_dout[111:96]}};

assign p_Val2_114_fu_404_p4 = {{layer6_out_dout[127:112]}};

assign p_Val2_115_fu_414_p4 = {{layer6_out_dout[143:128]}};

assign p_Val2_116_fu_424_p4 = {{layer6_out_dout[159:144]}};

assign p_Val2_117_fu_434_p4 = {{layer6_out_dout[175:160]}};

assign p_Val2_118_fu_444_p4 = {{layer6_out_dout[191:176]}};

assign p_Val2_119_fu_454_p4 = {{layer6_out_dout[207:192]}};

assign p_Val2_120_fu_464_p4 = {{layer6_out_dout[223:208]}};

assign p_Val2_192_fu_334_p4 = {{layer6_out_dout[255:240]}};

assign p_Val2_193_fu_374_p4 = {{layer6_out_dout[79:64]}};

assign p_Val2_194_fu_480_p4 = {{layer6_out_dout[9:4]}};

assign p_Val2_195_fu_614_p4 = {{layer6_out_dout[25:20]}};

assign p_Val2_196_fu_754_p4 = {{layer6_out_dout[41:36]}};

assign p_Val2_197_fu_894_p4 = {{layer6_out_dout[57:52]}};

assign p_Val2_198_fu_1034_p4 = {{layer6_out_dout[73:68]}};

assign p_Val2_199_fu_1174_p4 = {{layer6_out_dout[89:84]}};

assign p_Val2_200_fu_1314_p4 = {{layer6_out_dout[105:100]}};

assign p_Val2_201_fu_1454_p4 = {{layer6_out_dout[121:116]}};

assign p_Val2_202_fu_1594_p4 = {{layer6_out_dout[137:132]}};

assign p_Val2_203_fu_1734_p4 = {{layer6_out_dout[153:148]}};

assign p_Val2_204_fu_1874_p4 = {{layer6_out_dout[169:164]}};

assign p_Val2_205_fu_2014_p4 = {{layer6_out_dout[185:180]}};

assign p_Val2_206_fu_2154_p4 = {{layer6_out_dout[201:196]}};

assign p_Val2_207_fu_2294_p4 = {{layer6_out_dout[217:212]}};

assign p_Val2_270_fu_540_p2 = (p_Val2_194_fu_480_p4 + zext_ln377_fu_536_p1);

assign p_Val2_272_fu_680_p2 = (p_Val2_195_fu_614_p4 + zext_ln377_128_fu_676_p1);

assign p_Val2_274_fu_820_p2 = (p_Val2_196_fu_754_p4 + zext_ln377_129_fu_816_p1);

assign p_Val2_276_fu_960_p2 = (p_Val2_197_fu_894_p4 + zext_ln377_130_fu_956_p1);

assign p_Val2_277_fu_1100_p2 = (p_Val2_198_fu_1034_p4 + zext_ln377_131_fu_1096_p1);

assign p_Val2_278_fu_1240_p2 = (p_Val2_199_fu_1174_p4 + zext_ln377_132_fu_1236_p1);

assign p_Val2_279_fu_1380_p2 = (p_Val2_200_fu_1314_p4 + zext_ln377_133_fu_1376_p1);

assign p_Val2_280_fu_1520_p2 = (p_Val2_201_fu_1454_p4 + zext_ln377_134_fu_1516_p1);

assign p_Val2_281_fu_1660_p2 = (p_Val2_202_fu_1594_p4 + zext_ln377_135_fu_1656_p1);

assign p_Val2_282_fu_1800_p2 = (p_Val2_203_fu_1734_p4 + zext_ln377_136_fu_1796_p1);

assign p_Val2_283_fu_1940_p2 = (p_Val2_204_fu_1874_p4 + zext_ln377_137_fu_1936_p1);

assign p_Val2_284_fu_2080_p2 = (p_Val2_205_fu_2014_p4 + zext_ln377_138_fu_2076_p1);

assign p_Val2_285_fu_2220_p2 = (p_Val2_206_fu_2154_p4 + zext_ln377_139_fu_2216_p1);

assign p_Val2_286_fu_2360_p2 = (p_Val2_207_fu_2294_p4 + zext_ln377_140_fu_2356_p1);

assign p_Val2_287_fu_324_p4 = {{layer6_out_dout[239:224]}};

assign p_Val2_288_fu_2434_p4 = {{layer6_out_dout[233:228]}};

assign p_Val2_289_fu_2500_p2 = (p_Val2_288_fu_2434_p4 + zext_ln377_141_fu_2496_p1);

assign p_Val2_290_fu_2574_p4 = {{layer6_out_dout[249:244]}};

assign p_Val2_291_fu_2640_p2 = (p_Val2_290_fu_2574_p4 + zext_ln377_142_fu_2636_p1);

assign r_128_fu_650_p2 = ((tmp_252_fu_640_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_129_fu_790_p2 = ((tmp_254_fu_780_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_130_fu_930_p2 = ((tmp_256_fu_920_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_131_fu_1070_p2 = ((tmp_fu_1060_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_132_fu_1210_p2 = ((tmp_259_fu_1200_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_133_fu_1350_p2 = ((tmp_261_fu_1340_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_134_fu_1490_p2 = ((tmp_263_fu_1480_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_135_fu_1630_p2 = ((tmp_265_fu_1620_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_136_fu_1770_p2 = ((tmp_267_fu_1760_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_137_fu_1910_p2 = ((tmp_269_fu_1900_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_138_fu_2050_p2 = ((tmp_271_fu_2040_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_139_fu_2190_p2 = ((tmp_273_fu_2180_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_140_fu_2330_p2 = ((tmp_275_fu_2320_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_141_fu_2470_p2 = ((tmp_277_fu_2460_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_142_fu_2610_p2 = ((tmp_279_fu_2600_p4 != 3'd0) ? 1'b1 : 1'b0);

assign r_fu_510_p2 = ((trunc_ln828_fu_506_p1 != 3'd0) ? 1'b1 : 1'b0);

assign select_ln1649_120_fu_1860_p3 = ((icmp_ln1649_136_fu_1728_p2[0:0] == 1'b1) ? select_ln302_120_fu_1852_p3 : 6'd0);

assign select_ln1649_121_fu_2000_p3 = ((icmp_ln1649_137_fu_1868_p2[0:0] == 1'b1) ? select_ln302_121_fu_1992_p3 : 6'd0);

assign select_ln1649_122_fu_2140_p3 = ((icmp_ln1649_138_fu_2008_p2[0:0] == 1'b1) ? select_ln302_122_fu_2132_p3 : 6'd0);

assign select_ln1649_123_fu_2280_p3 = ((icmp_ln1649_139_fu_2148_p2[0:0] == 1'b1) ? select_ln302_123_fu_2272_p3 : 6'd0);

assign select_ln1649_124_fu_2420_p3 = ((icmp_ln1649_140_fu_2288_p2[0:0] == 1'b1) ? select_ln302_124_fu_2412_p3 : 6'd0);

assign select_ln1649_125_fu_2560_p3 = ((icmp_ln1649_141_fu_2428_p2[0:0] == 1'b1) ? select_ln302_125_fu_2552_p3 : 6'd0);

assign select_ln1649_126_fu_2700_p3 = ((icmp_ln1649_142_fu_2568_p2[0:0] == 1'b1) ? select_ln302_126_fu_2692_p3 : 6'd0);

assign select_ln1649_fu_1720_p3 = ((icmp_ln1649_135_fu_1588_p2[0:0] == 1'b1) ? select_ln302_fu_1712_p3 : 6'd0);

assign select_ln302_120_fu_1852_p3 = ((deleted_zeros_136_fu_1844_p3[0:0] == 1'b1) ? p_Val2_282_fu_1800_p2 : 6'd63);

assign select_ln302_121_fu_1992_p3 = ((deleted_zeros_137_fu_1984_p3[0:0] == 1'b1) ? p_Val2_283_fu_1940_p2 : 6'd63);

assign select_ln302_122_fu_2132_p3 = ((deleted_zeros_138_fu_2124_p3[0:0] == 1'b1) ? p_Val2_284_fu_2080_p2 : 6'd63);

assign select_ln302_123_fu_2272_p3 = ((deleted_zeros_139_fu_2264_p3[0:0] == 1'b1) ? p_Val2_285_fu_2220_p2 : 6'd63);

assign select_ln302_124_fu_2412_p3 = ((deleted_zeros_140_fu_2404_p3[0:0] == 1'b1) ? p_Val2_286_fu_2360_p2 : 6'd63);

assign select_ln302_125_fu_2552_p3 = ((deleted_zeros_141_fu_2544_p3[0:0] == 1'b1) ? p_Val2_289_fu_2500_p2 : 6'd63);

assign select_ln302_126_fu_2692_p3 = ((deleted_zeros_142_fu_2684_p3[0:0] == 1'b1) ? p_Val2_291_fu_2640_p2 : 6'd63);

assign select_ln302_fu_1712_p3 = ((deleted_zeros_135_fu_1704_p3[0:0] == 1'b1) ? p_Val2_281_fu_1660_p2 : 6'd63);

assign select_ln888_128_fu_716_p3 = ((tmp_654_fu_708_p3[0:0] == 1'b1) ? Range1_all_zeros_128_fu_702_p2 : Range1_all_ones_128_fu_696_p2);

assign select_ln888_129_fu_856_p3 = ((tmp_658_fu_848_p3[0:0] == 1'b1) ? Range1_all_zeros_129_fu_842_p2 : Range1_all_ones_129_fu_836_p2);

assign select_ln888_130_fu_996_p3 = ((tmp_662_fu_988_p3[0:0] == 1'b1) ? Range1_all_zeros_130_fu_982_p2 : Range1_all_ones_130_fu_976_p2);

assign select_ln888_131_fu_1136_p3 = ((tmp_666_fu_1128_p3[0:0] == 1'b1) ? Range1_all_zeros_131_fu_1122_p2 : Range1_all_ones_131_fu_1116_p2);

assign select_ln888_132_fu_1276_p3 = ((tmp_670_fu_1268_p3[0:0] == 1'b1) ? Range1_all_zeros_132_fu_1262_p2 : Range1_all_ones_132_fu_1256_p2);

assign select_ln888_133_fu_1416_p3 = ((tmp_674_fu_1408_p3[0:0] == 1'b1) ? Range1_all_zeros_133_fu_1402_p2 : Range1_all_ones_133_fu_1396_p2);

assign select_ln888_134_fu_1556_p3 = ((tmp_678_fu_1548_p3[0:0] == 1'b1) ? Range1_all_zeros_134_fu_1542_p2 : Range1_all_ones_134_fu_1536_p2);

assign select_ln888_135_fu_1696_p3 = ((tmp_682_fu_1688_p3[0:0] == 1'b1) ? Range1_all_zeros_135_fu_1682_p2 : Range1_all_ones_135_fu_1676_p2);

assign select_ln888_136_fu_1836_p3 = ((tmp_686_fu_1828_p3[0:0] == 1'b1) ? Range1_all_zeros_136_fu_1822_p2 : Range1_all_ones_136_fu_1816_p2);

assign select_ln888_137_fu_1976_p3 = ((tmp_690_fu_1968_p3[0:0] == 1'b1) ? Range1_all_zeros_137_fu_1962_p2 : Range1_all_ones_137_fu_1956_p2);

assign select_ln888_138_fu_2116_p3 = ((tmp_694_fu_2108_p3[0:0] == 1'b1) ? Range1_all_zeros_138_fu_2102_p2 : Range1_all_ones_138_fu_2096_p2);

assign select_ln888_139_fu_2256_p3 = ((tmp_698_fu_2248_p3[0:0] == 1'b1) ? Range1_all_zeros_139_fu_2242_p2 : Range1_all_ones_139_fu_2236_p2);

assign select_ln888_140_fu_2396_p3 = ((tmp_702_fu_2388_p3[0:0] == 1'b1) ? Range1_all_zeros_140_fu_2382_p2 : Range1_all_ones_140_fu_2376_p2);

assign select_ln888_141_fu_2536_p3 = ((tmp_706_fu_2528_p3[0:0] == 1'b1) ? Range1_all_zeros_141_fu_2522_p2 : Range1_all_ones_141_fu_2516_p2);

assign select_ln888_142_fu_2676_p3 = ((tmp_710_fu_2668_p3[0:0] == 1'b1) ? Range1_all_zeros_142_fu_2662_p2 : Range1_all_ones_142_fu_2656_p2);

assign select_ln888_fu_576_p3 = ((tmp_650_fu_568_p3[0:0] == 1'b1) ? Range1_all_zeros_fu_562_p2 : Range1_all_ones_fu_556_p2);

assign start_out = real_start;

assign tmp_252_fu_640_p4 = {{layer6_out_dout[18:16]}};

assign tmp_253_fu_686_p4 = {{layer6_out_dout[31:26]}};

assign tmp_254_fu_780_p4 = {{layer6_out_dout[34:32]}};

assign tmp_255_fu_826_p4 = {{layer6_out_dout[47:42]}};

assign tmp_256_fu_920_p4 = {{layer6_out_dout[50:48]}};

assign tmp_257_fu_966_p4 = {{layer6_out_dout[63:58]}};

assign tmp_258_fu_1106_p4 = {{layer6_out_dout[79:74]}};

assign tmp_259_fu_1200_p4 = {{layer6_out_dout[82:80]}};

assign tmp_260_fu_1246_p4 = {{layer6_out_dout[95:90]}};

assign tmp_261_fu_1340_p4 = {{layer6_out_dout[98:96]}};

assign tmp_262_fu_1386_p4 = {{layer6_out_dout[111:106]}};

assign tmp_263_fu_1480_p4 = {{layer6_out_dout[114:112]}};

assign tmp_264_fu_1526_p4 = {{layer6_out_dout[127:122]}};

assign tmp_265_fu_1620_p4 = {{layer6_out_dout[130:128]}};

assign tmp_266_fu_1666_p4 = {{layer6_out_dout[143:138]}};

assign tmp_267_fu_1760_p4 = {{layer6_out_dout[146:144]}};

assign tmp_268_fu_1806_p4 = {{layer6_out_dout[159:154]}};

assign tmp_269_fu_1900_p4 = {{layer6_out_dout[162:160]}};

assign tmp_270_fu_1946_p4 = {{layer6_out_dout[175:170]}};

assign tmp_271_fu_2040_p4 = {{layer6_out_dout[178:176]}};

assign tmp_272_fu_2086_p4 = {{layer6_out_dout[191:186]}};

assign tmp_273_fu_2180_p4 = {{layer6_out_dout[194:192]}};

assign tmp_274_fu_2226_p4 = {{layer6_out_dout[207:202]}};

assign tmp_275_fu_2320_p4 = {{layer6_out_dout[210:208]}};

assign tmp_276_fu_2366_p4 = {{layer6_out_dout[223:218]}};

assign tmp_277_fu_2460_p4 = {{layer6_out_dout[226:224]}};

assign tmp_278_fu_2506_p4 = {{layer6_out_dout[239:234]}};

assign tmp_279_fu_2600_p4 = {{layer6_out_dout[242:240]}};

assign tmp_280_fu_2646_p4 = {{layer6_out_dout[255:250]}};

assign tmp_650_fu_568_p3 = p_Val2_270_fu_540_p2[32'd5];

assign tmp_654_fu_708_p3 = p_Val2_272_fu_680_p2[32'd5];

assign tmp_658_fu_848_p3 = p_Val2_274_fu_820_p2[32'd5];

assign tmp_662_fu_988_p3 = p_Val2_276_fu_960_p2[32'd5];

assign tmp_666_fu_1128_p3 = p_Val2_277_fu_1100_p2[32'd5];

assign tmp_670_fu_1268_p3 = p_Val2_278_fu_1240_p2[32'd5];

assign tmp_674_fu_1408_p3 = p_Val2_279_fu_1380_p2[32'd5];

assign tmp_678_fu_1548_p3 = p_Val2_280_fu_1520_p2[32'd5];

assign tmp_682_fu_1688_p3 = p_Val2_281_fu_1660_p2[32'd5];

assign tmp_686_fu_1828_p3 = p_Val2_282_fu_1800_p2[32'd5];

assign tmp_690_fu_1968_p3 = p_Val2_283_fu_1940_p2[32'd5];

assign tmp_694_fu_2108_p3 = p_Val2_284_fu_2080_p2[32'd5];

assign tmp_698_fu_2248_p3 = p_Val2_285_fu_2220_p2[32'd5];

assign tmp_702_fu_2388_p3 = p_Val2_286_fu_2360_p2[32'd5];

assign tmp_706_fu_2528_p3 = p_Val2_289_fu_2500_p2[32'd5];

assign tmp_710_fu_2668_p3 = p_Val2_291_fu_2640_p2[32'd5];

assign tmp_fu_1060_p4 = {{layer6_out_dout[66:64]}};

assign tmp_s_fu_546_p4 = {{layer6_out_dout[15:10]}};

assign trunc_ln828_fu_506_p1 = layer6_out_dout[2:0];

assign zext_ln377_128_fu_676_p1 = and_ln374_128_fu_670_p2;

assign zext_ln377_129_fu_816_p1 = and_ln374_129_fu_810_p2;

assign zext_ln377_130_fu_956_p1 = and_ln374_130_fu_950_p2;

assign zext_ln377_131_fu_1096_p1 = and_ln374_131_fu_1090_p2;

assign zext_ln377_132_fu_1236_p1 = and_ln374_132_fu_1230_p2;

assign zext_ln377_133_fu_1376_p1 = and_ln374_133_fu_1370_p2;

assign zext_ln377_134_fu_1516_p1 = and_ln374_134_fu_1510_p2;

assign zext_ln377_135_fu_1656_p1 = and_ln374_135_fu_1650_p2;

assign zext_ln377_136_fu_1796_p1 = and_ln374_136_fu_1790_p2;

assign zext_ln377_137_fu_1936_p1 = and_ln374_137_fu_1930_p2;

assign zext_ln377_138_fu_2076_p1 = and_ln374_138_fu_2070_p2;

assign zext_ln377_139_fu_2216_p1 = and_ln374_139_fu_2210_p2;

assign zext_ln377_140_fu_2356_p1 = and_ln374_140_fu_2350_p2;

assign zext_ln377_141_fu_2496_p1 = and_ln374_141_fu_2490_p2;

assign zext_ln377_142_fu_2636_p1 = and_ln374_142_fu_2630_p2;

assign zext_ln377_fu_536_p1 = and_ln374_fu_530_p2;

endmodule //kernel_wrapper_relu_array_ap_fixed_16u_array_ap_ufixed_6_0_4_0_0_16u_relu_config8_s
